// teams.c
#include "teams.h" // Include the header to get the 'Team' type

#if defined(PBL_COLOR)
const Team TEAMS[] = {
  { .logo_res_id = RESOURCE_ID_ACC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_AIRFORCE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 10 },
  { .logo_res_id = RESOURCE_ID_AKRON, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 54 },
  { .logo_res_id = RESOURCE_ID_ALABAMA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 11 },
  { .logo_res_id = RESOURCE_ID_AMERICAN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_APPSTATE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 40 },
  { .logo_res_id = RESOURCE_ID_ARIZONA, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 7 },
  { .logo_res_id = RESOURCE_ID_ARIZONAST, .color = GColorChromeYellowARGB8, .icon_color = GColorWhiteARGB8, .rival = 6 },
  { .logo_res_id = RESOURCE_ID_ARKANSAS, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 60 },
  { .logo_res_id = RESOURCE_ID_ARKANSASST, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 64 },
  { .logo_res_id = RESOURCE_ID_ARMY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 76 },
  { .logo_res_id = RESOURCE_ID_AUBURN, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 3 },
  { .logo_res_id = RESOURCE_ID_B1G, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_BALLST, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 66 },
  { .logo_res_id = RESOURCE_ID_BAYLOR, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 114 },
  { .logo_res_id = RESOURCE_ID_BIG12, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_BOISEST, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_BOSTONCOLLEGE, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 86 },
  { .logo_res_id = RESOURCE_ID_BOWLINGGREEN, .color = GColorOrangeARGB8, .icon_color = GColorBlackARGB8, .rival = 121 },
  { .logo_res_id = RESOURCE_ID_BUFFALO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 115 },
  { .logo_res_id = RESOURCE_ID_BYU, .color = GColorCobaltBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 138 },
  { .logo_res_id = RESOURCE_ID_CAL, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 111 },
  { .logo_res_id = RESOURCE_ID_CENTRALMICHIGAN, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 148 },
  { .logo_res_id = RESOURCE_ID_CFB, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_CHAOS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_CINCI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 66 },
  { .logo_res_id = RESOURCE_ID_CLEMSON, .color = GColorOrangeARGB8, .icon_color = GColorWhiteARGB8, .rival = 108 },
  { .logo_res_id = RESOURCE_ID_COASTAL, .color = GColorTiffanyBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 58 },
  { .logo_res_id = RESOURCE_ID_COLORADO, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 29 },
  { .logo_res_id = RESOURCE_ID_COLORADOST, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 28 },
  { .logo_res_id = RESOURCE_ID_CUSA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_DELEWARE, .color = GColorCobaltBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 128 },
  { .logo_res_id = RESOURCE_ID_DUKE, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 134 },
  { .logo_res_id = RESOURCE_ID_EASTERNMICHIGAN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 22 },
  { .logo_res_id = RESOURCE_ID_ECU, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 62 },
  { .logo_res_id = RESOURCE_ID_FAU, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 36 },
  { .logo_res_id = RESOURCE_ID_FIU, .color = GColorOxfordBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 35 },
  { .logo_res_id = RESOURCE_ID_FLORIDA, .color = GColorDukeBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 39 },
  { .logo_res_id = RESOURCE_ID_FRESNOST, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 105 },
  { .logo_res_id = RESOURCE_ID_FSU, .color = GColorBulgarianRoseARGB8, .icon_color = GColorBlackARGB8, .rival = 37 },
  { .logo_res_id = RESOURCE_ID_GEORGIASOUTHERN, .color = GColorOxfordBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 41 },
  { .logo_res_id = RESOURCE_ID_GEORGIAST, .color = GColorCobaltBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 40 },
  { .logo_res_id = RESOURCE_ID_GEORGIATECH, .color = GColorBrassARGB8, .icon_color = GColorBlackARGB8, .rival = 129 }, // Fixed!
  { .logo_res_id = RESOURCE_ID_HAWAII, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_HOUSTON, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 99 },
  { .logo_res_id = RESOURCE_ID_ILLINOIS, .color = GColorOrangeARGB8, .icon_color = GColorWhiteARGB8, .rival = 85 },
  { .logo_res_id = RESOURCE_ID_INDEPENDENT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_INDIANA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 98 },
  { .logo_res_id = RESOURCE_ID_IOWA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 49 },
  { .logo_res_id = RESOURCE_ID_IOWAST, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 48 },
  { .logo_res_id = RESOURCE_ID_JAXST, .color = GColorRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 122 },
  { .logo_res_id = RESOURCE_ID_JMU, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 87 },
  { .logo_res_id = RESOURCE_ID_KANSAS, .color = GColorBlueMoonARGB8, .icon_color = GColorBlackARGB8, .rival = 74 },
  { .logo_res_id = RESOURCE_ID_KENNESAWST, .color = GColorChromeYellowARGB8, .icon_color = GColorWhiteARGB8, .rival = 41 },
  { .logo_res_id = RESOURCE_ID_KENTST, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 2 },
  { .logo_res_id = RESOURCE_ID_KENTUCKY, .color = GColorDukeBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 59 },
  { .logo_res_id = RESOURCE_ID_KSTATE, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 52 },
  { .logo_res_id = RESOURCE_ID_LATECH, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 110 },
  { .logo_res_id = RESOURCE_ID_LIBERTY, .color = GColorOxfordBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 51 },
  { .logo_res_id = RESOURCE_ID_LOUISVILLE, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 55 },
  { .logo_res_id = RESOURCE_ID_LSU, .color = GColorYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 3 },
  { .logo_res_id = RESOURCE_ID_MAC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_MARSHALL, .color = GColorJaegerGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 34 },
  { .logo_res_id = RESOURCE_ID_MARYLAND, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 96 },
  { .logo_res_id = RESOURCE_ID_MEMPHIS, .color = GColorCobaltBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 125 },
  { .logo_res_id = RESOURCE_ID_METEOR, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_MIAMIOH, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorBlackARGB8, .rival = 25 },
  { .logo_res_id = RESOURCE_ID_MIAMI, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 39 },
  { .logo_res_id = RESOURCE_ID_MICHIGAN, .color = GColorOxfordBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 93 },
  { .logo_res_id = RESOURCE_ID_MICHIGANST, .color = GColorMidnightGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 68 },
  { .logo_res_id = RESOURCE_ID_MIDTENNST, .color = GColorCobaltBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 150 },
  { .logo_res_id = RESOURCE_ID_MINNESOTA, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 149 },
  { .logo_res_id = RESOURCE_ID_MISSOURIST, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 8 },
  { .logo_res_id = RESOURCE_ID_MISSST, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 90 },
  { .logo_res_id = RESOURCE_ID_MISSOURI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 52 },
  { .logo_res_id = RESOURCE_ID_MW, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_NAVY, .color = GColorOxfordBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 10 },
  { .logo_res_id = RESOURCE_ID_NCAA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_NCST, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 134 },
  { .logo_res_id = RESOURCE_ID_NDSU, .color = GColorMidnightGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 152 },
  { .logo_res_id = RESOURCE_ID_NEBRASKA, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 48 },
  { .logo_res_id = RESOURCE_ID_NEVADA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 135 },
  { .logo_res_id = RESOURCE_ID_NEWMEXICO, .color = GColorRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 83 },
  { .logo_res_id = RESOURCE_ID_NEWMEXICOST, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 82 },
  { .logo_res_id = RESOURCE_ID_NIU, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 13 },
  { .logo_res_id = RESOURCE_ID_NORTHWESTERN, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 45 },
  { .logo_res_id = RESOURCE_ID_NOTREDAME, .color = GColorDarkGreenARGB8, .icon_color = GColorBlackARGB8, .rival = 109 },
  { .logo_res_id = RESOURCE_ID_ODU, .color = GColorDukeBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 51 },
  { .logo_res_id = RESOURCE_ID_OHIO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 66 },
  { .logo_res_id = RESOURCE_ID_OKST, .color = GColorOrangeARGB8, .icon_color = GColorWhiteARGB8, .rival = 94 },
  { .logo_res_id = RESOURCE_ID_OLEMISS, .color = GColorDukeBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 73 },
  { .logo_res_id = RESOURCE_ID_OREGON, .color = GColorYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 146 },
  { .logo_res_id = RESOURCE_ID_OREGONST, .color = GColorOrangeARGB8, .icon_color = GColorBlackARGB8, .rival = 91 },
  { .logo_res_id = RESOURCE_ID_OHIOST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 68 },
  { .logo_res_id = RESOURCE_ID_OKLAHOMA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 117 },
  { .logo_res_id = RESOURCE_ID_PAC12, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_PENNST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 93 },
  { .logo_res_id = RESOURCE_ID_PITT, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 151 },
  { .logo_res_id = RESOURCE_ID_PURDUE, .color = GColorPastelYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 47 },
  { .logo_res_id = RESOURCE_ID_RICE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 44 },
  { .logo_res_id = RESOURCE_ID_RUTGERS, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 63 },
  { .logo_res_id = RESOURCE_ID_SACST, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_SHSU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 119 },
  { .logo_res_id = RESOURCE_ID_SDSU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_SEC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_SJSU, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_SMU, .color = GColorDukeBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 114 },
  { .logo_res_id = RESOURCE_ID_USA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 122 },
  { .logo_res_id = RESOURCE_ID_GAMECOCK, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 26 },
  { .logo_res_id = RESOURCE_ID_SOUTHERNCAL, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 86 },
  { .logo_res_id = RESOURCE_ID_SOUTHERNMISS, .color = GColorYellowARGB8, .icon_color = GColorWhiteARGB8, .rival = 57 },
  { .logo_res_id = RESOURCE_ID_STANFORD, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 21 },
  { .logo_res_id = RESOURCE_ID_SUNBELT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_SYRACUSE, .color = GColorOrangeARGB8, .icon_color = GColorBlackARGB8, .rival = 97 },
  { .logo_res_id = RESOURCE_ID_TCU, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 14 },
  { .logo_res_id = RESOURCE_ID_TEMPLE, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 19 },
  { .logo_res_id = RESOURCE_ID_TENNESSEE, .color = GColorOrangeARGB8, .icon_color = GColorWhiteARGB8, .rival = 3 },
  { .logo_res_id = RESOURCE_ID_TEXAS, .color = GColorWindsorTanARGB8, .icon_color = GColorWhiteARGB8, .rival = 94 },
  { .logo_res_id = RESOURCE_ID_ATM, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 117 },
  { .logo_res_id = RESOURCE_ID_TEXASST, .color = GColorBulgarianRoseARGB8, .icon_color = GColorBlackARGB8, .rival = 141 },
  { .logo_res_id = RESOURCE_ID_TEXASTECH, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 117 },
  { .logo_res_id = RESOURCE_ID_TOLEDO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 18 },
  { .logo_res_id = RESOURCE_ID_TROY, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 107 },
  { .logo_res_id = RESOURCE_ID_TULANE, .color = GColorDarkGreenARGB8, .icon_color = GColorBlackARGB8, .rival = 110 },
  { .logo_res_id = RESOURCE_ID_TULSA, .color = GColorBrassARGB8, .icon_color = GColorBlackARGB8, .rival = 89 },
  { .logo_res_id = RESOURCE_ID_UAB, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 64 },
  { .logo_res_id = RESOURCE_ID_UCF, .color = GColorBrassARGB8, .icon_color = GColorWhiteARGB8, .rival = 137 },
  { .logo_res_id = RESOURCE_ID_UCLA, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 109 },
  { .logo_res_id = RESOURCE_ID_UCONN, .color = GColorOxfordBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 132 },
  { .logo_res_id = RESOURCE_ID_UGA, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorBlackARGB8, .rival = 42 },
  { .logo_res_id = RESOURCE_ID_ULL, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 131 },
  { .logo_res_id = RESOURCE_ID_ULM, .color = GColorBulgarianRoseARGB8, .icon_color = GColorBlackARGB8, .rival = 130 },
  { .logo_res_id = RESOURCE_ID_UMASS, .color = GColorBulgarianRoseARGB8, .icon_color = GColorBlackARGB8, .rival = 128 },
  { .logo_res_id = RESOURCE_ID_UNCC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 5 },
  { .logo_res_id = RESOURCE_ID_UNC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 32 },
  { .logo_res_id = RESOURCE_ID_UNLV, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorBlackARGB8, .rival = 81 },
  { .logo_res_id = RESOURCE_ID_UNT, .color = GColorJaegerGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 141 },
  { .logo_res_id = RESOURCE_ID_USF, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 126 },
  { .logo_res_id = RESOURCE_ID_UTAH, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 20 },
  { .logo_res_id = RESOURCE_ID_UTAHST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 138 },
  { .logo_res_id = RESOURCE_ID_UTEP, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 83 },
  { .logo_res_id = RESOURCE_ID_UTSA, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 119 },
  { .logo_res_id = RESOURCE_ID_UVA, .color = GColorOrangeARGB8, .icon_color = GColorBlackARGB8, .rival = 144 },
  { .logo_res_id = RESOURCE_ID_VANDY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 116 },
  { .logo_res_id = RESOURCE_ID_VT, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 142 },
  { .logo_res_id = RESOURCE_ID_WAKE, .color = GColorBrassARGB8, .icon_color = GColorBlackARGB8, .rival = 78 },
  { .logo_res_id = RESOURCE_ID_WASHINGTON, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 91 },
  { .logo_res_id = RESOURCE_ID_WASHINGTONST, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 146 },
  { .logo_res_id = RESOURCE_ID_WESTERNMICHIGAN, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 22 },
  { .logo_res_id = RESOURCE_ID_WISCONSIN, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 71 },
  { .logo_res_id = RESOURCE_ID_WKU, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorBlackARGB8, .rival = 70 },
  { .logo_res_id = RESOURCE_ID_WVU, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 97 },
  { .logo_res_id = RESOURCE_ID_WYOMING, .color = GColorWindsorTanARGB8, .icon_color = GColorWhiteARGB8, .rival = 29 },
};
#else
const Team TEAMS[] = {
  { .logo_res_id = RESOURCE_ID_ACC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_AIRFORCE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 10 },
  { .logo_res_id = RESOURCE_ID_AKRON, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 54 },
  { .logo_res_id = RESOURCE_ID_ALABAMA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 11 },
  { .logo_res_id = RESOURCE_ID_AMERICAN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_APPSTATE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 40 },
  { .logo_res_id = RESOURCE_ID_ARIZONA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 7 },
  { .logo_res_id = RESOURCE_ID_ARIZONAST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 6 },
  { .logo_res_id = RESOURCE_ID_ARKANSAS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 60 },
  { .logo_res_id = RESOURCE_ID_ARKANSASST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 64 },
  { .logo_res_id = RESOURCE_ID_ARMY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 76 },
  { .logo_res_id = RESOURCE_ID_AUBURN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 3 },
  { .logo_res_id = RESOURCE_ID_B1G, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_BALLST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 66 },
  { .logo_res_id = RESOURCE_ID_BAYLOR, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 114 },
  { .logo_res_id = RESOURCE_ID_BIG12, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_BOISEST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_BOSTONCOLLEGE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 86 },
  { .logo_res_id = RESOURCE_ID_BOWLINGGREEN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 121 },
  { .logo_res_id = RESOURCE_ID_BUFFALO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 115 },
  { .logo_res_id = RESOURCE_ID_BYU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 138 },
  { .logo_res_id = RESOURCE_ID_CAL, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 111 },
  { .logo_res_id = RESOURCE_ID_CENTRALMICHIGAN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 148 },
  { .logo_res_id = RESOURCE_ID_CFB, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_CHAOS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_CINCI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 66 },
  { .logo_res_id = RESOURCE_ID_CLEMSON, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 108 },
  { .logo_res_id = RESOURCE_ID_COASTAL, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 58 },
  { .logo_res_id = RESOURCE_ID_COLORADO, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 29 },
  { .logo_res_id = RESOURCE_ID_COLORADOST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 28 },
  { .logo_res_id = RESOURCE_ID_CUSA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_DELEWARE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 128 },
  { .logo_res_id = RESOURCE_ID_DUKE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 134 },
  { .logo_res_id = RESOURCE_ID_EASTERNMICHIGAN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 22 },
  { .logo_res_id = RESOURCE_ID_ECU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 62 },
  { .logo_res_id = RESOURCE_ID_FAU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 36 },
  { .logo_res_id = RESOURCE_ID_FIU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 35 },
  { .logo_res_id = RESOURCE_ID_FLORIDA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 39 },
  { .logo_res_id = RESOURCE_ID_FRESNOST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 105 },
  { .logo_res_id = RESOURCE_ID_FSU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 37 },
  { .logo_res_id = RESOURCE_ID_GEORGIASOUTHERN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 41 },
  { .logo_res_id = RESOURCE_ID_GEORGIAST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 40 },
  { .logo_res_id = RESOURCE_ID_GEORGIATECH, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 129 },
  { .logo_res_id = RESOURCE_ID_HAWAII, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_HOUSTON, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 99 },
  { .logo_res_id = RESOURCE_ID_ILLINOIS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 85 },
  { .logo_res_id = RESOURCE_ID_INDEPENDENT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_INDIANA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 98 },
  { .logo_res_id = RESOURCE_ID_IOWA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 49 },
  { .logo_res_id = RESOURCE_ID_IOWAST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 48 },
  { .logo_res_id = RESOURCE_ID_JAXST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 122 },
  { .logo_res_id = RESOURCE_ID_JMU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 87 },
  { .logo_res_id = RESOURCE_ID_KANSAS, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 74 },
  { .logo_res_id = RESOURCE_ID_KENNESAWST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 41 },
  { .logo_res_id = RESOURCE_ID_KENTST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 2 },
  { .logo_res_id = RESOURCE_ID_KENTUCKY, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 59 },
  { .logo_res_id = RESOURCE_ID_KSTATE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 52 },
  { .logo_res_id = RESOURCE_ID_LATECH, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 110 },
  { .logo_res_id = RESOURCE_ID_LIBERTY, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 51 },
  { .logo_res_id = RESOURCE_ID_LOUISVILLE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 55 },
  { .logo_res_id = RESOURCE_ID_LSU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 3 },
  { .logo_res_id = RESOURCE_ID_MAC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_MARSHALL, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 34 },
  { .logo_res_id = RESOURCE_ID_MARYLAND, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 96 },
  { .logo_res_id = RESOURCE_ID_MEMPHIS, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 125 },
  { .logo_res_id = RESOURCE_ID_METEOR, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_MIAMIOH, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 25 },
  { .logo_res_id = RESOURCE_ID_MIAMI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 39 },
  { .logo_res_id = RESOURCE_ID_MICHIGAN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 93 },
  { .logo_res_id = RESOURCE_ID_MICHIGANST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 68 },
  { .logo_res_id = RESOURCE_ID_MIDTENNST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 150 },
  { .logo_res_id = RESOURCE_ID_MINNESOTA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 149 },
  { .logo_res_id = RESOURCE_ID_MISSOURIST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 8 },
  { .logo_res_id = RESOURCE_ID_MISSST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 90 },
  { .logo_res_id = RESOURCE_ID_MISSOURI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 52 },
  { .logo_res_id = RESOURCE_ID_MW, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_NAVY, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 10 },
  { .logo_res_id = RESOURCE_ID_NCAA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_NCST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 134 },
  { .logo_res_id = RESOURCE_ID_NDSU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 152 },
  { .logo_res_id = RESOURCE_ID_NEBRASKA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 48 },
  { .logo_res_id = RESOURCE_ID_NEVADA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 135 },
  { .logo_res_id = RESOURCE_ID_NEWMEXICO, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 83 },
  { .logo_res_id = RESOURCE_ID_NEWMEXICOST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 82 },
  { .logo_res_id = RESOURCE_ID_NIU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 13 },
  { .logo_res_id = RESOURCE_ID_NORTHWESTERN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 45 },
  { .logo_res_id = RESOURCE_ID_NOTREDAME, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 109 },
  { .logo_res_id = RESOURCE_ID_ODU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 51 },
  { .logo_res_id = RESOURCE_ID_OHIO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 66 },
  { .logo_res_id = RESOURCE_ID_OKST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 94 },
  { .logo_res_id = RESOURCE_ID_OLEMISS, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 73 },
  { .logo_res_id = RESOURCE_ID_OREGON, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 146 },
  { .logo_res_id = RESOURCE_ID_OREGONST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 91 },
  { .logo_res_id = RESOURCE_ID_OHIOST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 68 },
  { .logo_res_id = RESOURCE_ID_OKLAHOMA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 117 },
  { .logo_res_id = RESOURCE_ID_PAC12, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_PENNST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 93 },
  { .logo_res_id = RESOURCE_ID_PITT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 151 },
  { .logo_res_id = RESOURCE_ID_PURDUE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 47 },
  { .logo_res_id = RESOURCE_ID_RICE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 44 },
  { .logo_res_id = RESOURCE_ID_RUTGERS, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 63 },
  { .logo_res_id = RESOURCE_ID_SACST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_SHSU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 119 },
  { .logo_res_id = RESOURCE_ID_SDSU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_SEC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_SJSU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 38 },
  { .logo_res_id = RESOURCE_ID_SMU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 114 },
  { .logo_res_id = RESOURCE_ID_USA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 122 },
  { .logo_res_id = RESOURCE_ID_GAMECOCK, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 26 },
  { .logo_res_id = RESOURCE_ID_SOUTHERNCAL, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 86 },
  { .logo_res_id = RESOURCE_ID_SOUTHERNMISS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 57 },
  { .logo_res_id = RESOURCE_ID_STANFORD, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 21 },
  { .logo_res_id = RESOURCE_ID_SUNBELT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77 },
  { .logo_res_id = RESOURCE_ID_SYRACUSE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 97 },
  { .logo_res_id = RESOURCE_ID_TCU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 14 },
  { .logo_res_id = RESOURCE_ID_TEMPLE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 19 },
  { .logo_res_id = RESOURCE_ID_TENNESSEE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 3 },
  { .logo_res_id = RESOURCE_ID_TEXAS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 94 },
  { .logo_res_id = RESOURCE_ID_ATM, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 117 },
  { .logo_res_id = RESOURCE_ID_TEXASST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 141 },
  { .logo_res_id = RESOURCE_ID_TEXASTECH, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 117 },
  { .logo_res_id = RESOURCE_ID_TOLEDO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 18 },
  { .logo_res_id = RESOURCE_ID_TROY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 107 },
  { .logo_res_id = RESOURCE_ID_TULANE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 110 },
  { .logo_res_id = RESOURCE_ID_TULSA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 89 },
  { .logo_res_id = RESOURCE_ID_UAB, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 64 },
  { .logo_res_id = RESOURCE_ID_UCF, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 137 },
  { .logo_res_id = RESOURCE_ID_UCLA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 109 },
  { .logo_res_id = RESOURCE_ID_UCONN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 132 },
  { .logo_res_id = RESOURCE_ID_UGA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 42 },
  { .logo_res_id = RESOURCE_ID_ULL, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 131 },
  { .logo_res_id = RESOURCE_ID_ULM, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 130 },
  { .logo_res_id = RESOURCE_ID_UMASS, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 128 },
  { .logo_res_id = RESOURCE_ID_UNCC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 5 },
  { .logo_res_id = RESOURCE_ID_UNC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 32 },
  { .logo_res_id = RESOURCE_ID_UNLV, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 81 },
  { .logo_res_id = RESOURCE_ID_UNT, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 141 },
  { .logo_res_id = RESOURCE_ID_USF, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 126 },
};
#endif

/*
#if defined(PBL_COLOR)
const Team TEAMS[] = {
  { .logo_res_id = RESOURCE_ID_ACC, .color = GColorWhiteARGB8, .name = "ACC" },
  { .logo_res_id = RESOURCE_ID_AIRFORCE, .color = GColorWhiteARGB8, .name = "Air Force" },
  { .logo_res_id = RESOURCE_ID_AKRON, .color = GColorOxfordBlueARGB8, .name = "Akron" },
  { .logo_res_id = RESOURCE_ID_ALABAMA, .color = GColorWhiteARGB8, .name = "Alabama" },
  { .logo_res_id = RESOURCE_ID_AMERICAN, .color = GColorWhiteARGB8, .name = "American" },
  { .logo_res_id = RESOURCE_ID_APPSTATE, .color = GColorBlackARGB8, .name = "App State" },
  { .logo_res_id = RESOURCE_ID_ARIZONA, .color = GColorOxfordBlueARGB8, .name = "Arizona" },
  { .logo_res_id = RESOURCE_ID_ARIZONAST, .color = GColorChromeYellowARGB8, .name = "Arizona State" },
  { .logo_res_id = RESOURCE_ID_ARKANSAS, .color = GColorDarkCandyAppleRedARGB8, .name = "Arkansas" },
  { .logo_res_id = RESOURCE_ID_ARKANSASST, .color = GColorDarkCandyAppleRedARGB8, .name = "Arkansas State" },
  { .logo_res_id = RESOURCE_ID_ARMY, .color = GColorDarkGrayARGB8, .name = "Army" },
  { .logo_res_id = RESOURCE_ID_AUBURN, .color = GColorOxfordBlueARGB8, .name = "Auburn" },
  { .logo_res_id = RESOURCE_ID_B1G, .color = GColorWhiteARGB8, .name = "B1G" },
  { .logo_res_id = RESOURCE_ID_BALLST, .color = GColorDarkCandyAppleRedARGB8, .name = "Ball State" },
  { .logo_res_id = RESOURCE_ID_BAYLOR, .color = GColorChromeYellowARGB8, .name = "Baylor" },
  { .logo_res_id = RESOURCE_ID_BIG12, .color = GColorWhiteARGB8, .name = "BIG 12" },
  { .logo_res_id = RESOURCE_ID_BOISEST, .color = GColorDukeBlueARGB8, .name = "Boise State" },
  { .logo_res_id = RESOURCE_ID_BOSTONCOLLEGE, .color = GColorDarkCandyAppleRedARGB8, .name = "Boston College" },
  { .logo_res_id = RESOURCE_ID_BOWLINGGREEN, .color = GColorOrangeARGB8, .name = "Bowling Green" },
  { .logo_res_id = RESOURCE_ID_BUFFALO, .color = GColorWhiteARGB8, .name = "Buffalo" },
  { .logo_res_id = RESOURCE_ID_BYU, .color = GColorCobaltBlueARGB8, .name = "BYU" },
  { .logo_res_id = RESOURCE_ID_CAL, .color = GColorChromeYellowARGB8, .name = "California" },
  { .logo_res_id = RESOURCE_ID_CENTRALMICHIGAN, .color = GColorChromeYellowARGB8, .name = "Central Michigan" },
  { .logo_res_id = RESOURCE_ID_CFB, .color = GColorWhiteARGB8, .name = "CFB" },
  { .logo_res_id = RESOURCE_ID_CHAOS, .color = GColorBlackARGB8, .name = "Chaos" },
  { .logo_res_id = RESOURCE_ID_CINCI, .color = GColorBlackARGB8, .name = "Cincinnati" },
  { .logo_res_id = RESOURCE_ID_CLEMSON, .color = GColorOrangeARGB8, .name = "Clemson" },
  { .logo_res_id = RESOURCE_ID_COASTAL, .color = GColorTiffanyBlueARGB8, .name = "Coastal Carolina" },
  { .logo_res_id = RESOURCE_ID_COLORADO, .color = GColorBlackARGB8, .name = "Colorado" },
  { .logo_res_id = RESOURCE_ID_COLORADOST, .color = GColorDarkGreenARGB8, .name = "Colorado State" },
  { .logo_res_id = RESOURCE_ID_CUSA, .color = GColorWhiteARGB8, .name = "CUSA" },
  { .logo_res_id = RESOURCE_ID_DELEWARE, .color = GColorCobaltBlueARGB8, .name = "Deleware" },
  { .logo_res_id = RESOURCE_ID_DUKE, .color = GColorDukeBlueARGB8, .name = "Duke" },
  { .logo_res_id = RESOURCE_ID_EASTERNMICHIGAN, .color = GColorBlackARGB8, .name = "Eastern Michigan" },
  { .logo_res_id = RESOURCE_ID_ECU, .color = GColorIndigoARGB8, .name = "East Carolina" },
  { .logo_res_id = RESOURCE_ID_FAU, .color = GColorOxfordBlueARGB8, .name = "FAU" },
  { .logo_res_id = RESOURCE_ID_FIU, .color = GColorOxfordBlueARGB8, .name = "Florida International" },
  { .logo_res_id = RESOURCE_ID_FLORIDA, .color = GColorDukeBlueARGB8, .name = "Florida" },
  { .logo_res_id = RESOURCE_ID_FRESNOST, .color = GColorRedARGB8, .name = "Fresno State" },
  { .logo_res_id = RESOURCE_ID_FSU, .color = GColorBulgarianRoseARGB8, .name = "Florida State" },
  { .logo_res_id = RESOURCE_ID_GEORGIASOUTHERN, .color = GColorOxfordBlueARGB8, .name = "Georgia Southern" },
  { .logo_res_id = RESOURCE_ID_GEORGIAST, .color = GColorCobaltBlueARGB8, .name = "Georgia State" },
  { .logo_res_id = RESOURCE_ID_GEORGIATECH, .color = GColorBrassARGB8, .name = "Georgia Tech" },
  { .logo_res_id = RESOURCE_ID_HAWAII, .color = GColorDarkGreenARGB8, .name = "Hawaii" },
  { .logo_res_id = RESOURCE_ID_HOUSTON, .color = GColorRedARGB8, .name = "Houston" },
  { .logo_res_id = RESOURCE_ID_ILLINOIS, .color = GColorOrangeARGB8, .name = "Illinois" },
  { .logo_res_id = RESOURCE_ID_INDEPENDENT, .color = GColorWhiteARGB8, .name = "Independent" },
  { .logo_res_id = RESOURCE_ID_INDIANA, .color = GColorWhiteARGB8, .name = "Indiana" },
  { .logo_res_id = RESOURCE_ID_IOWA, .color = GColorWhiteARGB8, .name = "Iowa" },
  { .logo_res_id = RESOURCE_ID_IOWAST, .color = GColorDarkCandyAppleRedARGB8, .name = "Iowa State" },
  { .logo_res_id = RESOURCE_ID_JAXST, .color = GColorRedARGB8, .name = "Jacksonville State" },
  { .logo_res_id = RESOURCE_ID_JMU, .color = GColorIndigoARGB8, .name = "James Maddison" },
  { .logo_res_id = RESOURCE_ID_KANSAS, .color = GColorBlueMoonARGB8, .name = "Kansas" },
  { .logo_res_id = RESOURCE_ID_KENNESAWST, .color = GColorChromeYellowARGB8, .name = "Kennesaw State" },
  { .logo_res_id = RESOURCE_ID_KENTST, .color = GColorDukeBlueARGB8, .name = "Kent State" },
  { .logo_res_id = RESOURCE_ID_KENTUCKY, .color = GColorDukeBlueARGB8, .name = "Kentucky" },
  { .logo_res_id = RESOURCE_ID_KSTATE, .color = GColorIndigoARGB8, .name = "Kansas State" },
  { .logo_res_id = RESOURCE_ID_LATECH, .color = GColorRedARGB8, .name = "LA Tech" },
  { .logo_res_id = RESOURCE_ID_LIBERTY, .color = GColorOxfordBlueARGB8, .name = "Liberty" },
  { .logo_res_id = RESOURCE_ID_LOUISVILLE, .color = GColorRedARGB8, .name = "Louisville" },
  { .logo_res_id = RESOURCE_ID_LSU, .color = GColorYellowARGB8, .name = "LSU" },
  { .logo_res_id = RESOURCE_ID_MAC, .color = GColorWhiteARGB8, .name = "MAC" },
  { .logo_res_id = RESOURCE_ID_MARSHALL, .color = GColorJaegerGreenARGB8, .name = "Marshall" },
  { .logo_res_id = RESOURCE_ID_MARYLAND, .color = GColorRedARGB8, .name = "Maryland" },
  { .logo_res_id = RESOURCE_ID_MEMPHIS, .color = GColorCobaltBlueARGB8, .name = "Memphis" },
  { .logo_res_id = RESOURCE_ID_METEOR, .color = GColorWhiteARGB8, .name = "Meteor" },
  { .logo_res_id = RESOURCE_ID_MIAMIOH, .color = GColorDarkCandyAppleRedARGB8, .name = "Miami Ohio" },
  { .logo_res_id = RESOURCE_ID_MIAMI, .color = GColorDarkGreenARGB8, .name = "Miami" },
  { .logo_res_id = RESOURCE_ID_MICHIGAN, .color = GColorOxfordBlueARGB8, .name = "Michigan" },
  { .logo_res_id = RESOURCE_ID_MICHIGANST, .color = GColorMidnightGreenARGB8, .name = "Michigan State" },
  { .logo_res_id = RESOURCE_ID_MIDTENNST, .color = GColorCobaltBlueARGB8, .name = "Middle Tennessee State" },
  { .logo_res_id = RESOURCE_ID_MINNESOTA, .color = GColorBulgarianRoseARGB8, .name = "Minnesota" },
  { .logo_res_id = RESOURCE_ID_MISSOURIST, .color = GColorBulgarianRoseARGB8, .name = "Missouri State" },
  { .logo_res_id = RESOURCE_ID_MISSST, .color = GColorBulgarianRoseARGB8, .name = "Mississippi State" },
  { .logo_res_id = RESOURCE_ID_MISSOURI, .color = GColorBlackARGB8, .name = "Missouri" },
  { .logo_res_id = RESOURCE_ID_MW, .color = GColorWhiteARGB8, .name = "Mountain West" },
  { .logo_res_id = RESOURCE_ID_NAVY, .color = GColorOxfordBlueARGB8, .name = "Navy" },
  { .logo_res_id = RESOURCE_ID_NCAA, .color = GColorWhiteARGB8, .name = "NCAA" },
  { .logo_res_id = RESOURCE_ID_NCST, .color = GColorRedARGB8, .name = "North Carolina State" },
  { .logo_res_id = RESOURCE_ID_NDSU, .color = GColorMidnightGreenARGB8, .name = "North Dakota State" },
  { .logo_res_id = RESOURCE_ID_NEBRASKA, .color = GColorRedARGB8, .name = "Nebraska" },
  { .logo_res_id = RESOURCE_ID_NEVADA, .color = GColorWhiteARGB8, .name = "Nevada" },
  { .logo_res_id = RESOURCE_ID_NEWMEXICO, .color = GColorRedARGB8, .name = "New Mexico" },
  { .logo_res_id = RESOURCE_ID_NEWMEXICOST, .color = GColorBulgarianRoseARGB8, .name = "New Mexico State" },
  { .logo_res_id = RESOURCE_ID_NIU, .color = GColorDarkCandyAppleRedARGB8, .name = "NIU" },
  { .logo_res_id = RESOURCE_ID_NORTHWESTERN, .color = GColorIndigoARGB8, .name = "Northwestern" },
  { .logo_res_id = RESOURCE_ID_NOTREDAME, .color = GColorDarkGreenARGB8, .name = "Notre Dame" },
  { .logo_res_id = RESOURCE_ID_ODU, .color = GColorDukeBlueARGB8, .name = "Old Dominion" },
  { .logo_res_id = RESOURCE_ID_OHIO, .color = GColorWhiteARGB8, .name = "Ohio" },
  { .logo_res_id = RESOURCE_ID_OKST, .color = GColorOrangeARGB8, .name = "Oklahoma State" },
  { .logo_res_id = RESOURCE_ID_OLEMISS, .color = GColorDukeBlueARGB8, .name = "Ole Miss" },
  { .logo_res_id = RESOURCE_ID_OREGON, .color = GColorYellowARGB8, .name = "Oregon" },
  { .logo_res_id = RESOURCE_ID_OREGONST, .color = GColorOrangeARGB8, .name = "Oregon State" },
  { .logo_res_id = RESOURCE_ID_OHIOST, .color = GColorWhiteARGB8, .name = "Ohio State" },
  { .logo_res_id = RESOURCE_ID_OKLAHOMA, .color = GColorWhiteARGB8, .name = "Oklahoma" },
  { .logo_res_id = RESOURCE_ID_PAC12, .color = GColorWhiteARGB8, .name = "PAC 12" },
  { .logo_res_id = RESOURCE_ID_PENNST, .color = GColorWhiteARGB8, .name = "Penn State" },
  { .logo_res_id = RESOURCE_ID_PITT, .color = GColorChromeYellowARGB8, .name = "Pitt" },
  { .logo_res_id = RESOURCE_ID_PURDUE, .color = GColorPastelYellowARGB8, .name = "Purdue" },
  { .logo_res_id = RESOURCE_ID_RICE, .color = GColorWhiteARGB8, .name = "Rice" },
  { .logo_res_id = RESOURCE_ID_RUTGERS, .color = GColorRedARGB8, .name = "Rutgers" },
  { .logo_res_id = RESOURCE_ID_SACST, .color = GColorDarkGreenARGB8, .name = "Sacramento State" },
  { .logo_res_id = RESOURCE_ID_SHSU, .color = GColorWhiteARGB8, .name = "SHSU" },
  { .logo_res_id = RESOURCE_ID_SDSU, .color = GColorWhiteARGB8, .name = "SDSU" },
  { .logo_res_id = RESOURCE_ID_SEC, .color = GColorWhiteARGB8, .name = "SEC" },
  { .logo_res_id = RESOURCE_ID_SJSU, .color = GColorDukeBlueARGB8, .name = "SJSU" },
  { .logo_res_id = RESOURCE_ID_SMU, .color = GColorDukeBlueARGB8, .name = "SMU" },
  { .logo_res_id = RESOURCE_ID_USA, .color = GColorWhiteARGB8, .name = "South Alabama" },
  { .logo_res_id = RESOURCE_ID_GAMECOCK, .color = GColorDarkCandyAppleRedARGB8, .name = "South Carolina" },
  { .logo_res_id = RESOURCE_ID_SOUTHERNCAL, .color = GColorDarkCandyAppleRedARGB8, .name = "Southern Cal" },
  { .logo_res_id = RESOURCE_ID_SOUTHERNMISS, .color = GColorYellowARGB8, .name = "Southern Miss" },
  { .logo_res_id = RESOURCE_ID_STANFORD, .color = GColorDarkCandyAppleRedARGB8, .name = "Stanford" },
  { .logo_res_id = RESOURCE_ID_SUNBELT, .color = GColorWhiteARGB8, .name = "Sun Belt" },
  { .logo_res_id = RESOURCE_ID_SYRACUSE, .color = GColorOrangeARGB8, .name = "Syracuse" },
  { .logo_res_id = RESOURCE_ID_TCU, .color = GColorIndigoARGB8, .name = "TCU" },
  { .logo_res_id = RESOURCE_ID_TEMPLE, .color = GColorDarkCandyAppleRedARGB8, .name = "Temple" },
  { .logo_res_id = RESOURCE_ID_TENNESSEE, .color = GColorOrangeARGB8, .name = "Tennessee" },
  { .logo_res_id = RESOURCE_ID_TEXAS, .color = GColorWindsorTanARGB8, .name = "Texas" },
  { .logo_res_id = RESOURCE_ID_ATM, .color = GColorBulgarianRoseARGB8, .name = "Texas A&M" },
  { .logo_res_id = RESOURCE_ID_TEXASST, .color = GColorBulgarianRoseARGB8, .name = "Texas State" },
  { .logo_res_id = RESOURCE_ID_TEXASTECH, .color = GColorRedARGB8, .name = "Texas Tech" },
  { .logo_res_id = RESOURCE_ID_TOLEDO, .color = GColorWhiteARGB8, .name = "Toledo" },
  { .logo_res_id = RESOURCE_ID_TROY, .color = GColorWhiteARGB8, .name = "Troy" },
  { .logo_res_id = RESOURCE_ID_TULANE, .color = GColorDarkGreenARGB8, .name = "Tulane" },
  { .logo_res_id = RESOURCE_ID_TULSA, .color = GColorBrassARGB8, .name = "Tulsa" },
  { .logo_res_id = RESOURCE_ID_UAB, .color = GColorDarkGreenARGB8, .name = "UAB" },
  { .logo_res_id = RESOURCE_ID_UCF, .color = GColorBrassARGB8, .name = "Central Florida" },
  { .logo_res_id = RESOURCE_ID_UCLA, .color = GColorChromeYellowARGB8, .name = "UCLA" },
  { .logo_res_id = RESOURCE_ID_UCONN, .color = GColorOxfordBlueARGB8, .name = "Connecticut" },
  { .logo_res_id = RESOURCE_ID_UGA, .color = GColorDarkCandyAppleRedARGB8, .name = "Georgia" },
  { .logo_res_id = RESOURCE_ID_ULL, .color = GColorRedARGB8, .name = "ULL" },
  { .logo_res_id = RESOURCE_ID_ULM, .color = GColorBulgarianRoseARGB8, .name = "ULM" },
  { .logo_res_id = RESOURCE_ID_UMASS, .color = GColorBulgarianRoseARGB8, .name = "Massachusetts" },
  { .logo_res_id = RESOURCE_ID_UNCC, .color = GColorWhiteARGB8, .name = "Charlotte" },
  { .logo_res_id = RESOURCE_ID_UNC, .color = GColorWhiteARGB8, .name = "North Carolina" },
  { .logo_res_id = RESOURCE_ID_UNLV, .color = GColorDarkCandyAppleRedARGB8, .name = "UNLV" },
  { .logo_res_id = RESOURCE_ID_UNT, .color = GColorJaegerGreenARGB8, .name = "North Texas" },
  { .logo_res_id = RESOURCE_ID_USF, .color = GColorDarkGreenARGB8, .name = "South Florida" },
  { .logo_res_id = RESOURCE_ID_UTAH, .color = GColorDarkCandyAppleRedARGB8, .name = "Utah" },
  { .logo_res_id = RESOURCE_ID_UTAHST, .color = GColorWhiteARGB8, .name = "Utah State" },
  { .logo_res_id = RESOURCE_ID_UTEP, .color = GColorWhiteARGB8, .name = "UTEP" },
  { .logo_res_id = RESOURCE_ID_UTSA, .color = GColorOxfordBlueARGB8, .name = "UTSA" },
  { .logo_res_id = RESOURCE_ID_UVA, .color = GColorOrangeARGB8, .name = "Virginia" },
  { .logo_res_id = RESOURCE_ID_VANDY, .color = GColorBlackARGB8, .name = "Vanderbilt" },
  { .logo_res_id = RESOURCE_ID_VT, .color = GColorBulgarianRoseARGB8, .name = "Virginia Tech" },
  { .logo_res_id = RESOURCE_ID_WAKE, .color = GColorBrassARGB8, .name = "Wake Forest" },
  { .logo_res_id = RESOURCE_ID_WASHINGTON, .color = GColorIndigoARGB8, .name = "Washington" },
  { .logo_res_id = RESOURCE_ID_WASHINGTONST, .color = GColorDarkCandyAppleRedARGB8, .name = "Washington State" },
  { .logo_res_id = RESOURCE_ID_WESTERNMICHIGAN, .color = GColorBulgarianRoseARGB8, .name = "Western Michigan" },
  { .logo_res_id = RESOURCE_ID_WISCONSIN, .color = GColorDarkCandyAppleRedARGB8, .name = "Wisconsin" },
  { .logo_res_id = RESOURCE_ID_WKU, .color = GColorDarkCandyAppleRedARGB8, .name = "Western Kentucky" },
  { .logo_res_id = RESOURCE_ID_WVU, .color = GColorChromeYellowARGB8, .name = "West Virginia" },
  { .logo_res_id = RESOURCE_ID_WYOMING, .color = GColorWindsorTanARGB8, .name = "Wyoming" },
};
#else
const Team TEAMS[] = {
  { .logo_res_id = RESOURCE_ID_ACC, .color = GColorWhiteARGB8, .name = "ACC" },
  { .logo_res_id = RESOURCE_ID_AIRFORCE, .color = GColorWhiteARGB8, .name = "Air Force" },
  { .logo_res_id = RESOURCE_ID_AKRON, .color = GColorBlackARGB8, .name = "Akron" },
  { .logo_res_id = RESOURCE_ID_ALABAMA, .color = GColorWhiteARGB8, .name = "Alabama" },
  { .logo_res_id = RESOURCE_ID_AMERICAN, .color = GColorWhiteARGB8, .name = "American" },
  { .logo_res_id = RESOURCE_ID_APPSTATE, .color = GColorBlackARGB8, .name = "App State" },
  { .logo_res_id = RESOURCE_ID_ARIZONA, .color = GColorBlackARGB8, .name = "Arizona" },
  { .logo_res_id = RESOURCE_ID_ARIZONAST, .color = GColorBlackARGB8, .name = "Arizona State" },
  { .logo_res_id = RESOURCE_ID_ARKANSAS, .color = GColorBlackARGB8, .name = "Arkansas" },
  { .logo_res_id = RESOURCE_ID_ARKANSASST, .color = GColorBlackARGB8, .name = "Arkansas State" },
  { .logo_res_id = RESOURCE_ID_ARMY, .color = GColorBlackARGB8, .name = "Army" },
  { .logo_res_id = RESOURCE_ID_AUBURN, .color = GColorBlackARGB8, .name = "Auburn" },
  { .logo_res_id = RESOURCE_ID_B1G, .color = GColorWhiteARGB8, .name = "B1G" },
  { .logo_res_id = RESOURCE_ID_BALLST, .color = GColorBlackARGB8, .name = "Ball State" },
  { .logo_res_id = RESOURCE_ID_BAYLOR, .color = GColorWhiteARGB8, .name = "Baylor" },
  { .logo_res_id = RESOURCE_ID_BIG12, .color = GColorWhiteARGB8, .name = "BIG 12" },
  { .logo_res_id = RESOURCE_ID_BOISEST, .color = GColorBlackARGB8, .name = "Boise State" },
  { .logo_res_id = RESOURCE_ID_BOSTONCOLLEGE, .color = GColorBlackARGB8, .name = "Boston College" },
  { .logo_res_id = RESOURCE_ID_BOWLINGGREEN, .color = GColorWhiteARGB8, .name = "Bowling Green" },
  { .logo_res_id = RESOURCE_ID_BUFFALO, .color = GColorWhiteARGB8, .name = "Buffalo" },
  { .logo_res_id = RESOURCE_ID_BYU, .color = GColorBlackARGB8, .name = "BYU" },
  { .logo_res_id = RESOURCE_ID_CAL, .color = GColorWhiteARGB8, .name = "California" },
  { .logo_res_id = RESOURCE_ID_CENTRALMICHIGAN, .color = GColorWhiteARGB8, .name = "Central Michigan" },
  { .logo_res_id = RESOURCE_ID_CFB, .color = GColorWhiteARGB8, .name = "CFB" },
  { .logo_res_id = RESOURCE_ID_CHAOS, .color = GColorBlackARGB8, .name = "Chaos" },
  { .logo_res_id = RESOURCE_ID_CINCI, .color = GColorBlackARGB8, .name = "Cincinnati" },
  { .logo_res_id = RESOURCE_ID_CLEMSON, .color = GColorBlackARGB8, .name = "Clemson" },
  { .logo_res_id = RESOURCE_ID_COASTAL, .color = GColorWhiteARGB8, .name = "Coastal Carolina" },
  { .logo_res_id = RESOURCE_ID_COLORADO, .color = GColorBlackARGB8, .name = "Colorado" },
  { .logo_res_id = RESOURCE_ID_COLORADOST, .color = GColorBlackARGB8, .name = "Colorado State" },
  { .logo_res_id = RESOURCE_ID_CUSA, .color = GColorWhiteARGB8, .name = "CUSA" },
  { .logo_res_id = RESOURCE_ID_DELEWARE, .color = GColorWhiteARGB8, .name = "Deleware" },
  { .logo_res_id = RESOURCE_ID_DUKE, .color = GColorBlackARGB8, .name = "Duke" },
  { .logo_res_id = RESOURCE_ID_EASTERNMICHIGAN, .color = GColorBlackARGB8, .name = "Eastern Michigan" },
  { .logo_res_id = RESOURCE_ID_ECU, .color = GColorBlackARGB8, .name = "East Carolina" },
  { .logo_res_id = RESOURCE_ID_FAU, .color = GColorBlackARGB8, .name = "FAU" },
  { .logo_res_id = RESOURCE_ID_FIU, .color = GColorWhiteARGB8, .name = "Florida International" },
  { .logo_res_id = RESOURCE_ID_FLORIDA, .color = GColorWhiteARGB8, .name = "Florida" },
  { .logo_res_id = RESOURCE_ID_FRESNOST, .color = GColorWhiteARGB8, .name = "Fresno State" },
  { .logo_res_id = RESOURCE_ID_FSU, .color = GColorWhiteARGB8, .name = "Florida State" },
  { .logo_res_id = RESOURCE_ID_GEORGIASOUTHERN, .color = GColorWhiteARGB8, .name = "Georgia Southern" },
  { .logo_res_id = RESOURCE_ID_GEORGIAST, .color = GColorWhiteARGB8, .name = "Georgia State" },
  { .logo_res_id = RESOURCE_ID_GEORGIATECH, .color = GColorWhiteARGB8, .name = "Georgia Tech" },
  { .logo_res_id = RESOURCE_ID_HAWAII, .color = GColorBlackARGB8, .name = "Hawaii" },
  { .logo_res_id = RESOURCE_ID_HOUSTON, .color = GColorWhiteARGB8, .name = "Houston" },
  { .logo_res_id = RESOURCE_ID_ILLINOIS, .color = GColorBlackARGB8, .name = "Illinois" },
  { .logo_res_id = RESOURCE_ID_INDEPENDENT, .color = GColorWhiteARGB8, .name = "Independent" },
  { .logo_res_id = RESOURCE_ID_INDIANA, .color = GColorWhiteARGB8, .name = "Indiana" },
  { .logo_res_id = RESOURCE_ID_IOWA, .color = GColorBlackARGB8, .name = "Iowa" },
  { .logo_res_id = RESOURCE_ID_IOWAST, .color = GColorBlackARGB8, .name = "Iowa State" },
  { .logo_res_id = RESOURCE_ID_JAXST, .color = GColorBlackARGB8, .name = "Jacksonville State" },
  { .logo_res_id = RESOURCE_ID_JMU, .color = GColorBlackARGB8, .name = "James Maddison" },
  { .logo_res_id = RESOURCE_ID_KANSAS, .color = GColorWhiteARGB8, .name = "Kansas" },
  { .logo_res_id = RESOURCE_ID_KENNESAWST, .color = GColorBlackARGB8, .name = "Kennesaw State" },
  { .logo_res_id = RESOURCE_ID_KENTST, .color = GColorBlackARGB8, .name = "Kent State" },
  { .logo_res_id = RESOURCE_ID_KENTUCKY, .color = GColorWhiteARGB8, .name = "Kentucky" },
  { .logo_res_id = RESOURCE_ID_KSTATE, .color = GColorBlackARGB8, .name = "Kansas State" },
  { .logo_res_id = RESOURCE_ID_LATECH, .color = GColorWhiteARGB8, .name = "LA Tech" },
  { .logo_res_id = RESOURCE_ID_LIBERTY, .color = GColorWhiteARGB8, .name = "Liberty" },
  { .logo_res_id = RESOURCE_ID_LOUISVILLE, .color = GColorWhiteARGB8, .name = "Louisville" },
  { .logo_res_id = RESOURCE_ID_LSU, .color = GColorWhiteARGB8, .name = "LSU" },
  { .logo_res_id = RESOURCE_ID_MAC, .color = GColorWhiteARGB8, .name = "MAC" },
  { .logo_res_id = RESOURCE_ID_MARSHALL, .color = GColorBlackARGB8, .name = "Marshall" },
  { .logo_res_id = RESOURCE_ID_MARYLAND, .color = GColorWhiteARGB8, .name = "Maryland" },
  { .logo_res_id = RESOURCE_ID_MEMPHIS, .color = GColorWhiteARGB8, .name = "Memphis" },
  { .logo_res_id = RESOURCE_ID_METEOR, .color = GColorWhiteARGB8, .name = "Meteor" },
  { .logo_res_id = RESOURCE_ID_MIAMIOH, .color = GColorWhiteARGB8, .name = "Miami Ohio" },
  { .logo_res_id = RESOURCE_ID_MIAMI, .color = GColorBlackARGB8, .name = "Miami" },
  { .logo_res_id = RESOURCE_ID_MICHIGAN, .color = GColorWhiteARGB8, .name = "Michigan" },
  { .logo_res_id = RESOURCE_ID_MICHIGANST, .color = GColorBlackARGB8, .name = "Michigan State" },
  { .logo_res_id = RESOURCE_ID_MIDTENNST, .color = GColorBlackARGB8, .name = "Middle Tennessee State" },
  { .logo_res_id = RESOURCE_ID_MINNESOTA, .color = GColorBlackARGB8, .name = "Minnesota" },
  { .logo_res_id = RESOURCE_ID_MISSOURIST, .color = GColorBlackARGB8, .name = "Missouri State" },
  { .logo_res_id = RESOURCE_ID_MISSST, .color = GColorBlackARGB8, .name = "Mississippi State" },
  { .logo_res_id = RESOURCE_ID_MISSOURI, .color = GColorBlackARGB8, .name = "Missouri" },
  { .logo_res_id = RESOURCE_ID_MW, .color = GColorWhiteARGB8, .name = "Mountain West" },
  { .logo_res_id = RESOURCE_ID_NAVY, .color = GColorWhiteARGB8, .name = "Navy" },
  { .logo_res_id = RESOURCE_ID_NCAA, .color = GColorWhiteARGB8, .name = "NCAA" },
  { .logo_res_id = RESOURCE_ID_NCST, .color = GColorWhiteARGB8, .name = "North Carolina State" },
  { .logo_res_id = RESOURCE_ID_NDSU, .color = GColorBlackARGB8, .name = "North Dakota State" },
  { .logo_res_id = RESOURCE_ID_NEBRASKA, .color = GColorWhiteARGB8, .name = "Nebraska" },
  { .logo_res_id = RESOURCE_ID_NEVADA, .color = GColorWhiteARGB8, .name = "Nevada" },
  { .logo_res_id = RESOURCE_ID_NEWMEXICO, .color = GColorBlackARGB8, .name = "New Mexico" },
  { .logo_res_id = RESOURCE_ID_NEWMEXICOST, .color = GColorBlackARGB8, .name = "New Mexico State" },
  { .logo_res_id = RESOURCE_ID_NIU, .color = GColorBlackARGB8, .name = "NIU" },
  { .logo_res_id = RESOURCE_ID_NORTHWESTERN, .color = GColorBlackARGB8, .name = "Northwestern" },
  { .logo_res_id = RESOURCE_ID_NOTREDAME, .color = GColorWhiteARGB8, .name = "Notre Dame" },
  { .logo_res_id = RESOURCE_ID_ODU, .color = GColorWhiteARGB8, .name = "Old Dominion" },
  { .logo_res_id = RESOURCE_ID_OHIO, .color = GColorWhiteARGB8, .name = "Ohio" },
  { .logo_res_id = RESOURCE_ID_OKST, .color = GColorBlackARGB8, .name = "Oklahoma State" },
  { .logo_res_id = RESOURCE_ID_OLEMISS, .color = GColorWhiteARGB8, .name = "Ole Miss" },
  { .logo_res_id = RESOURCE_ID_OREGON, .color = GColorWhiteARGB8, .name = "Oregon" },
  { .logo_res_id = RESOURCE_ID_OREGONST, .color = GColorWhiteARGB8, .name = "Oregon State" },
  { .logo_res_id = RESOURCE_ID_OHIOST, .color = GColorWhiteARGB8, .name = "Ohio State" },
  { .logo_res_id = RESOURCE_ID_OKLAHOMA, .color = GColorWhiteARGB8, .name = "Oklahoma" },
  { .logo_res_id = RESOURCE_ID_PAC12, .color = GColorWhiteARGB8, .name = "PAC 12" },
  { .logo_res_id = RESOURCE_ID_PENNST, .color = GColorWhiteARGB8, .name = "Penn State" },
  { .logo_res_id = RESOURCE_ID_PITT, .color = GColorWhiteARGB8, .name = "Pitt" },
  { .logo_res_id = RESOURCE_ID_PURDUE, .color = GColorWhiteARGB8, .name = "Purdue" },
  { .logo_res_id = RESOURCE_ID_RICE, .color = GColorWhiteARGB8, .name = "Rice" },
  { .logo_res_id = RESOURCE_ID_RUTGERS, .color = GColorWhiteARGB8, .name = "Rutgers" },
  { .logo_res_id = RESOURCE_ID_SACST, .color = GColorBlackARGB8, .name = "Sacramento State" },
  { .logo_res_id = RESOURCE_ID_SHSU, .color = GColorBlackARGB8, .name = "SHSU" },
  { .logo_res_id = RESOURCE_ID_SDSU, .color = GColorBlackARGB8, .name = "SDSU" },
  { .logo_res_id = RESOURCE_ID_SEC, .color = GColorWhiteARGB8, .name = "SEC" },
  { .logo_res_id = RESOURCE_ID_SJSU, .color = GColorBlackARGB8, .name = "SJSU" },
  { .logo_res_id = RESOURCE_ID_SMU, .color = GColorWhiteARGB8, .name = "SMU" },
  { .logo_res_id = RESOURCE_ID_USA, .color = GColorWhiteARGB8, .name = "South Alabama" },
  { .logo_res_id = RESOURCE_ID_GAMECOCK, .color = GColorBlackARGB8, .name = "South Carolina" },
  { .logo_res_id = RESOURCE_ID_SOUTHERNCAL, .color = GColorBlackARGB8, .name = "Southern Cal" },
  { .logo_res_id = RESOURCE_ID_SOUTHERNMISS, .color = GColorBlackARGB8, .name = "Southern Miss" },
  { .logo_res_id = RESOURCE_ID_STANFORD, .color = GColorBlackARGB8, .name = "Stanford" },
  { .logo_res_id = RESOURCE_ID_SUNBELT, .color = GColorWhiteARGB8, .name = "Sun Belt" },
  { .logo_res_id = RESOURCE_ID_SYRACUSE, .color = GColorWhiteARGB8, .name = "Syracuse" },
  { .logo_res_id = RESOURCE_ID_TCU, .color = GColorBlackARGB8, .name = "TCU" },
  { .logo_res_id = RESOURCE_ID_TEMPLE, .color = GColorBlackARGB8, .name = "Temple" },
  { .logo_res_id = RESOURCE_ID_TENNESSEE, .color = GColorBlackARGB8, .name = "Tennessee" },
  { .logo_res_id = RESOURCE_ID_TEXAS, .color = GColorBlackARGB8, .name = "Texas" },
  { .logo_res_id = RESOURCE_ID_ATM, .color = GColorBlackARGB8, .name = "Texas A&M" },
  { .logo_res_id = RESOURCE_ID_TEXASST, .color = GColorWhiteARGB8, .name = "Texas State" },
  { .logo_res_id = RESOURCE_ID_TEXASTECH, .color = GColorWhiteARGB8, .name = "Texas Tech" },
  { .logo_res_id = RESOURCE_ID_TOLEDO, .color = GColorWhiteARGB8, .name = "Toledo" },
  { .logo_res_id = RESOURCE_ID_TROY, .color = GColorBlackARGB8, .name = "Troy" },
  { .logo_res_id = RESOURCE_ID_TULANE, .color = GColorWhiteARGB8, .name = "Tulane" },
  { .logo_res_id = RESOURCE_ID_TULSA, .color = GColorWhiteARGB8, .name = "Tulsa" },
  { .logo_res_id = RESOURCE_ID_UAB, .color = GColorBlackARGB8, .name = "UAB" },
  { .logo_res_id = RESOURCE_ID_UCF, .color = GColorBlackARGB8, .name = "Central Florida" },
  { .logo_res_id = RESOURCE_ID_UCLA, .color = GColorWhiteARGB8, .name = "UCLA" },
  { .logo_res_id = RESOURCE_ID_UCONN, .color = GColorWhiteARGB8, .name = "Connecticut" },
  { .logo_res_id = RESOURCE_ID_UGA, .color = GColorWhiteARGB8, .name = "Georgia" },
  { .logo_res_id = RESOURCE_ID_ULL, .color = GColorWhiteARGB8, .name = "ULL" },
  { .logo_res_id = RESOURCE_ID_ULM, .color = GColorWhiteARGB8, .name = "ULM" },
  { .logo_res_id = RESOURCE_ID_UMASS, .color = GColorWhiteARGB8, .name = "Massachusetts" },
  { .logo_res_id = RESOURCE_ID_UNCC, .color = GColorWhiteARGB8, .name = "Charlotte" },
  { .logo_res_id = RESOURCE_ID_UNC, .color = GColorWhiteARGB8, .name = "North Carolina" },
  { .logo_res_id = RESOURCE_ID_UNLV, .color = GColorWhiteARGB8, .name = "UNLV" },
  { .logo_res_id = RESOURCE_ID_UNT, .color = GColorBlackARGB8, .name = "North Texas" },
  { .logo_res_id = RESOURCE_ID_USF, .color = GColorBlackARGB8, .name = "South Florida" },
  { .logo_res_id = RESOURCE_ID_UTAH, .color = GColorBlackARGB8, .name = "Utah" },
  { .logo_res_id = RESOURCE_ID_UTAHST, .color = GColorWhiteARGB8, .name = "Utah State" },
  { .logo_res_id = RESOURCE_ID_UTEP, .color = GColorWhiteARGB8, .name = "UTEP" },
  { .logo_res_id = RESOURCE_ID_UTSA, .color = GColorBlackARGB8, .name = "UTSA" },
  { .logo_res_id = RESOURCE_ID_UVA, .color = GColorWhiteARGB8, .name = "Virginia" },
  { .logo_res_id = RESOURCE_ID_VANDY, .color = GColorBlackARGB8, .name = "Vanderbilt" },
  { .logo_res_id = RESOURCE_ID_VT, .color = GColorBlackARGB8, .name = "Virginia Tech" },
  { .logo_res_id = RESOURCE_ID_WAKE, .color = GColorWhiteARGB8, .name = "Wake Forest" },
  { .logo_res_id = RESOURCE_ID_WASHINGTON, .color = GColorBlackARGB8, .name = "Washington" },
  { .logo_res_id = RESOURCE_ID_WASHINGTONST, .color = GColorBlackARGB8, .name = "Washington State" },
  { .logo_res_id = RESOURCE_ID_WESTERNMICHIGAN, .color = GColorBlackARGB8, .name = "Western Michigan" },
  { .logo_res_id = RESOURCE_ID_WISCONSIN, .color = GColorBlackARGB8, .name = "Wisconsin" },
  { .logo_res_id = RESOURCE_ID_WKU, .color = GColorWhiteARGB8, .name = "Western Kentucky" },
  { .logo_res_id = RESOURCE_ID_WVU, .color = GColorWhiteARGB8, .name = "West Virginia" },
  { .logo_res_id = RESOURCE_ID_WYOMING, .color = GColorBlackARGB8, .name = "Wyoming" },
};
#endif
*/

// Define the count based on the array
const size_t TEAMS_COUNT = sizeof(TEAMS) / sizeof(TEAMS[0]);