// teams.c
#include "teams.h" // Include the header to get the 'Team' type


#if defined(PBL_COLOR)
const Team TEAMS[] = {
  { .logo_res_id = RESOURCE_ID_ACC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_AIRFORCE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 10, .name="Air Force", .shortname="AFA " },
  { .logo_res_id = RESOURCE_ID_AKRON, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 54, .name="Akron", .shortname="AKRN" },
  { .logo_res_id = RESOURCE_ID_ALABAMA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 11, .name="Alabama", .shortname="BAMA" },
  { .logo_res_id = RESOURCE_ID_AMERICAN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_APPSTATE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 40, .name="App State", .shortname="APP " },
  { .logo_res_id = RESOURCE_ID_ARIZONA, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 7, .name="Arizona", .shortname="ZONA" },
  { .logo_res_id = RESOURCE_ID_ARIZONAST, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 6, .name="Arizona State", .shortname="ASU " },
  { .logo_res_id = RESOURCE_ID_ARKANSAS, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 60, .name="Arkansas", .shortname="ARK " },
  { .logo_res_id = RESOURCE_ID_ARKANSASST, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 64, .name="Arkansas State", .shortname="AKST" },
  { .logo_res_id = RESOURCE_ID_ARMY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 76, .name="Army", .shortname="ARMY" },
  { .logo_res_id = RESOURCE_ID_AUBURN, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 3, .name="Auburn", .shortname="AUB " },
  { .logo_res_id = RESOURCE_ID_B1G, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_BALLST, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 66, .name="Ball State", .shortname="BALL" },
  { .logo_res_id = RESOURCE_ID_BAYLOR, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 114, .name="Baylor", .shortname="BAY " },
  { .logo_res_id = RESOURCE_ID_BIG12, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_BOISEST, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 38, .name="Boise State", .shortname="BSU " },
  { .logo_res_id = RESOURCE_ID_BOSTONCOLLEGE, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 86, .name="Boston College", .shortname="BC  " },
  { .logo_res_id = RESOURCE_ID_BOWLINGGREEN, .color = GColorOrangeARGB8, .icon_color = GColorWhiteARGB8, .rival = 121, .name="Bowling Green", .shortname="BGSU" },
  { .logo_res_id = RESOURCE_ID_BUFFALO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 115, .name="Buffalo", .shortname="BUFF" },
  { .logo_res_id = RESOURCE_ID_BYU, .color = GColorCobaltBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 138, .name="BYU", .shortname="BYU " },
  { .logo_res_id = RESOURCE_ID_CAL, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 111, .name="California", .shortname="CAL " },
  { .logo_res_id = RESOURCE_ID_CENTRALMICHIGAN, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 148, .name="Central Michigan", .shortname="CMU " },
  { .logo_res_id = RESOURCE_ID_CFB, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_CHAOS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_CINCI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 66, .name="Cincinnati", .shortname="CIN " },
  { .logo_res_id = RESOURCE_ID_CLEMSON, .color = GColorOrangeARGB8, .icon_color = GColorWhiteARGB8, .rival = 108, .name="Clemson", .shortname="CLEM" },
  { .logo_res_id = RESOURCE_ID_COASTAL, .color = GColorTiffanyBlueARGB8, .icon_color = GColorBlackARGB8, .rival = 58, .name="Coastal Carolina", .shortname="CCU " },
  { .logo_res_id = RESOURCE_ID_COLORADO, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 29, .name="Colorado", .shortname="CU  " },
  { .logo_res_id = RESOURCE_ID_COLORADOST, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 28, .name="Colorado State", .shortname="CSU " },
  { .logo_res_id = RESOURCE_ID_CUSA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_DELEWARE, .color = GColorCobaltBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 128, .name="Delaware", .shortname="DEL " },
  { .logo_res_id = RESOURCE_ID_DUKE, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 134, .name="Duke", .shortname="DUKE" },
  { .logo_res_id = RESOURCE_ID_EASTERNMICHIGAN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 22, .name="Eastern Michigan", .shortname="EMU " },
  { .logo_res_id = RESOURCE_ID_ECU, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 62, .name="East Carolina", .shortname="ECU " },
  { .logo_res_id = RESOURCE_ID_FAU, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 36, .name="Florida Atlantic", .shortname="FAU " },
  { .logo_res_id = RESOURCE_ID_FIU, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 35, .name="Florida International", .shortname="FIU " },
  { .logo_res_id = RESOURCE_ID_FLORIDA, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 39, .name="Florida", .shortname="UF  " },
  { .logo_res_id = RESOURCE_ID_FRESNOST, .color = GColorRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 105, .name="Fresno State", .shortname="FRES" },
  { .logo_res_id = RESOURCE_ID_FSU, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 37, .name="Florida State", .shortname="FSU " },
  { .logo_res_id = RESOURCE_ID_GEORGIASOUTHERN, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 41, .name="Georgia Southern", .shortname="GASO" },
  { .logo_res_id = RESOURCE_ID_GEORGIAST, .color = GColorCobaltBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 40, .name="Georgia State", .shortname="GSU " },
  { .logo_res_id = RESOURCE_ID_GEORGIATECH, .color = GColorBrassARGB8, .icon_color = GColorBlackARGB8, .rival = 129, .name="Georgia Tech", .shortname="GT  " },
  { .logo_res_id = RESOURCE_ID_HAWAII, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 38, .name="Hawai'i", .shortname="HAW " },
  { .logo_res_id = RESOURCE_ID_HOUSTON, .color = GColorRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 99, .name="Houston", .shortname="HOU " },
  { .logo_res_id = RESOURCE_ID_ILLINOIS, .color = GColorOrangeARGB8, .icon_color = GColorBlackARGB8, .rival = 85, .name="Illinois", .shortname="ILL " },
  { .logo_res_id = RESOURCE_ID_INDEPENDENT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_INDIANA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 98, .name="Indiana", .shortname="IND " },
  { .logo_res_id = RESOURCE_ID_IOWA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 49, .name="Iowa", .shortname="IOWA" },
  { .logo_res_id = RESOURCE_ID_IOWAST, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 48, .name="Iowa State", .shortname="ISU " },
  { .logo_res_id = RESOURCE_ID_JAXST, .color = GColorRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 122, .name="Jacksonville State", .shortname="JSU " },
  { .logo_res_id = RESOURCE_ID_JMU, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 87, .name="James Madison", .shortname="JMU " },
  { .logo_res_id = RESOURCE_ID_KANSAS, .color = GColorBlueMoonARGB8, .icon_color = GColorWhiteARGB8, .rival = 74, .name="Kansas", .shortname="KU  " },
  { .logo_res_id = RESOURCE_ID_KENNESAWST, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 41, .name="Kennesaw State", .shortname="KSU " },
  { .logo_res_id = RESOURCE_ID_KENTST, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 2, .name="Kent State", .shortname="KENT" },
  { .logo_res_id = RESOURCE_ID_KENTUCKY, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 59, .name="Kentucky", .shortname="UK  " },
  { .logo_res_id = RESOURCE_ID_KSTATE, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 52, .name="Kansas State", .shortname="KSU " },
  { .logo_res_id = RESOURCE_ID_LATECH, .color = GColorRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 110, .name="Louisiana Tech", .shortname="LT  " },
  { .logo_res_id = RESOURCE_ID_LIBERTY, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 51, .name="Liberty", .shortname="LIB " },
  { .logo_res_id = RESOURCE_ID_LOUISVILLE, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 55, .name="Louisville", .shortname="LOU " },
  { .logo_res_id = RESOURCE_ID_LSU, .color = GColorYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 3, .name="LSU", .shortname="LSU " },
  { .logo_res_id = RESOURCE_ID_MAC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_MARSHALL, .color = GColorJaegerGreenARGB8, .icon_color = GColorBlackARGB8, .rival = 34, .name="Marshall", .shortname="HERD" },
  { .logo_res_id = RESOURCE_ID_MARYLAND, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 96, .name="Maryland", .shortname="MD  " },
  { .logo_res_id = RESOURCE_ID_MEMPHIS, .color = GColorCobaltBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 125, .name="Memphis", .shortname="MEM " },
  { .logo_res_id = RESOURCE_ID_METEOR, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_MIAMIOH, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 25, .name="Miami (OH)", .shortname="M-OH" },
  { .logo_res_id = RESOURCE_ID_MIAMI, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 39, .name="Miami", .shortname="MIA " },
  { .logo_res_id = RESOURCE_ID_MICHIGAN, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 93, .name="Michigan", .shortname="MICH" },
  { .logo_res_id = RESOURCE_ID_MICHIGANST, .color = GColorMidnightGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 68, .name="Michigan State", .shortname="MSU " },
  { .logo_res_id = RESOURCE_ID_MIDTENNST, .color = GColorCobaltBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 150, .name="Middle Tennessee", .shortname="MTSU" },
  { .logo_res_id = RESOURCE_ID_MINNESOTA, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 149, .name="Minnesota", .shortname="MINN" },
  { .logo_res_id = RESOURCE_ID_MISSOURIST, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 8, .name="Missouri State", .shortname="MOST" },
  { .logo_res_id = RESOURCE_ID_MISSST, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 90, .name="Mississippi State", .shortname="MSST" },
  { .logo_res_id = RESOURCE_ID_MISSOURI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 52, .name="Missouri", .shortname="MIZZ" },
  { .logo_res_id = RESOURCE_ID_MW, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_NAVY, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 10, .name="Navy", .shortname="NAVY" },
  { .logo_res_id = RESOURCE_ID_NCAA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_NCST, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 134, .name="NC State", .shortname="NCST" },
  { .logo_res_id = RESOURCE_ID_NDSU, .color = GColorMidnightGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 152, .name="North Dakota State", .shortname="NDSU" },
  { .logo_res_id = RESOURCE_ID_NEBRASKA, .color = GColorRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 48, .name="Nebraska", .shortname="NEB " },
  { .logo_res_id = RESOURCE_ID_NEVADA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 135, .name="Nevada", .shortname="NEV " },
  { .logo_res_id = RESOURCE_ID_NEWMEXICO, .color = GColorRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 83, .name="New Mexico", .shortname="UNM " },
  { .logo_res_id = RESOURCE_ID_NEWMEXICOST, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 82, .name="New Mexico State", .shortname="NMSU" },
  { .logo_res_id = RESOURCE_ID_NIU, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 13, .name="Northern Illinois", .shortname="NIU " },
  { .logo_res_id = RESOURCE_ID_NORTHWESTERN, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 45, .name="Northwestern", .shortname="NU  " },
  { .logo_res_id = RESOURCE_ID_NOTREDAME, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 109, .name="Notre Dame", .shortname="ND  " },
  { .logo_res_id = RESOURCE_ID_ODU, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 51, .name="Old Dominion", .shortname="ODU " },
  { .logo_res_id = RESOURCE_ID_OHIO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 66, .name="Ohio", .shortname="OHIO" },
  { .logo_res_id = RESOURCE_ID_OKST, .color = GColorOrangeARGB8, .icon_color = GColorBlackARGB8, .rival = 94, .name="Oklahoma State", .shortname="OKST" },
  { .logo_res_id = RESOURCE_ID_OLEMISS, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 73, .name="Ole Miss", .shortname="MISS" },
  { .logo_res_id = RESOURCE_ID_OREGON, .color = GColorYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 146, .name="Oregon", .shortname="ORE " },
  { .logo_res_id = RESOURCE_ID_OREGONST, .color = GColorOrangeARGB8, .icon_color = GColorBlackARGB8, .rival = 91, .name="Oregon State", .shortname="ORST" },
  { .logo_res_id = RESOURCE_ID_OHIOST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 68, .name="Ohio State", .shortname="OSU " },
  { .logo_res_id = RESOURCE_ID_OKLAHOMA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 117, .name="Oklahoma", .shortname="OU  " },
  { .logo_res_id = RESOURCE_ID_PAC12, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_PENNST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 93, .name="Penn State", .shortname="PSU " },
  { .logo_res_id = RESOURCE_ID_PITT, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 151, .name="Pittsburgh", .shortname="PITT" },
  { .logo_res_id = RESOURCE_ID_PURDUE, .color = GColorPastelYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 47, .name="Purdue", .shortname="PUR " },
  { .logo_res_id = RESOURCE_ID_RICE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 44, .name="Rice", .shortname="RICE" },
  { .logo_res_id = RESOURCE_ID_RUTGERS, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 63, .name="Rutgers", .shortname="RUTG" },
  { .logo_res_id = RESOURCE_ID_SACST, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 38, .name="Sacramento State", .shortname="SAC " },
  { .logo_res_id = RESOURCE_ID_SHSU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 119, .name="Sam Houston", .shortname="SHSU" },
  { .logo_res_id = RESOURCE_ID_SDSU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 38, .name="San Diego State", .shortname="SDSU" },
  { .logo_res_id = RESOURCE_ID_SEC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_SJSU, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 38, .name="San José State", .shortname="SJSU" },
  { .logo_res_id = RESOURCE_ID_SMU, .color = GColorDukeBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 114, .name="SMU", .shortname="SMU " },
  { .logo_res_id = RESOURCE_ID_USA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 122, .name="South Alabama", .shortname="USA " },
  { .logo_res_id = RESOURCE_ID_GAMECOCK, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 26, .name="South Carolina", .shortname="SC  " },
  { .logo_res_id = RESOURCE_ID_SOUTHERNCAL, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 86, .name="USC", .shortname="USC " },
  { .logo_res_id = RESOURCE_ID_SOUTHERNMISS, .color = GColorYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 57, .name="Southern Miss", .shortname="USM " },
  { .logo_res_id = RESOURCE_ID_STANFORD, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 21, .name="Stanford", .shortname="STAN" },
  { .logo_res_id = RESOURCE_ID_SUNBELT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_SYRACUSE, .color = GColorOrangeARGB8, .icon_color = GColorBlackARGB8, .rival = 97, .name="Syracuse", .shortname="CUSE" },
  { .logo_res_id = RESOURCE_ID_TCU, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 14, .name="TCU", .shortname="TCU " },
  { .logo_res_id = RESOURCE_ID_TEMPLE, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 19, .name="Temple", .shortname="TEMP" },
  { .logo_res_id = RESOURCE_ID_TENNESSEE, .color = GColorOrangeARGB8, .icon_color = GColorWhiteARGB8, .rival = 3, .name="Tennessee", .shortname="TENN" },
  { .logo_res_id = RESOURCE_ID_TEXAS, .color = GColorWindsorTanARGB8, .icon_color = GColorWhiteARGB8, .rival = 94, .name="Texas", .shortname="TEX " },
  { .logo_res_id = RESOURCE_ID_ATM, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 117, .name="Texas A&M", .shortname="A&M " },
  { .logo_res_id = RESOURCE_ID_TEXASST, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 141, .name="Texas State", .shortname="TXST" },
  { .logo_res_id = RESOURCE_ID_TEXASTECH, .color = GColorRedARGB8, .icon_color = GColorBlackARGB8, .rival = 117, .name="Texas Tech", .shortname="TTU " },
  { .logo_res_id = RESOURCE_ID_TOLEDO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 18, .name="Toledo", .shortname="TOL " },
  { .logo_res_id = RESOURCE_ID_TROY, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 107, .name="Troy", .shortname="TROY" },
  { .logo_res_id = RESOURCE_ID_TULANE, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 110, .name="Tulane", .shortname="TULN" },
  { .logo_res_id = RESOURCE_ID_TULSA, .color = GColorBrassARGB8, .icon_color = GColorBlackARGB8, .rival = 89, .name="Tulsa", .shortname="TLSA" },
  { .logo_res_id = RESOURCE_ID_UAB, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 64, .name="UAB", .shortname="UAB " },
  { .logo_res_id = RESOURCE_ID_UCF, .color = GColorBrassARGB8, .icon_color = GColorBlackARGB8, .rival = 137, .name="UCF", .shortname="UCF " },
  { .logo_res_id = RESOURCE_ID_UCLA, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 109, .name="UCLA", .shortname="UCLA" },
  { .logo_res_id = RESOURCE_ID_UCONN, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 132, .name="UConn", .shortname="CONN" },
  { .logo_res_id = RESOURCE_ID_UGA, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 42, .name="Georgia", .shortname="UGA " },
  { .logo_res_id = RESOURCE_ID_ULL, .color = GColorRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 131, .name="Louisiana", .shortname="ULL " },
  { .logo_res_id = RESOURCE_ID_ULM, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 130, .name="UL Monroe", .shortname="ULM " },
  { .logo_res_id = RESOURCE_ID_UMASS, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 128, .name="Massachusetts", .shortname="MASS" },
  { .logo_res_id = RESOURCE_ID_UNCC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 5, .name="Charlotte", .shortname="CLT " },
  { .logo_res_id = RESOURCE_ID_UNC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 32, .name="North Carolina", .shortname="UNC " },
  { .logo_res_id = RESOURCE_ID_UNLV, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 81, .name="UNLV", .shortname="UNLV" },
  { .logo_res_id = RESOURCE_ID_UNT, .color = GColorJaegerGreenARGB8, .icon_color = GColorBlackARGB8, .rival = 141, .name="North Texas", .shortname="UNT " },
  { .logo_res_id = RESOURCE_ID_USF, .color = GColorDarkGreenARGB8, .icon_color = GColorWhiteARGB8, .rival = 126, .name="South Florida", .shortname="USF " },
  { .logo_res_id = RESOURCE_ID_UTAH, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 20, .name="Utah", .shortname="UTAH" },
  { .logo_res_id = RESOURCE_ID_UTAHST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 138, .name="Utah State", .shortname="USU " },
  { .logo_res_id = RESOURCE_ID_UTEP, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 83, .name="UTEP", .shortname="UTEP" },
  { .logo_res_id = RESOURCE_ID_UTSA, .color = GColorOxfordBlueARGB8, .icon_color = GColorWhiteARGB8, .rival = 119, .name="UTSA", .shortname="UTSA" },
  { .logo_res_id = RESOURCE_ID_UVA, .color = GColorOrangeARGB8, .icon_color = GColorWhiteARGB8, .rival = 144, .name="Virginia", .shortname="UVA " },
  { .logo_res_id = RESOURCE_ID_VANDY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 116, .name="Vanderbilt", .shortname="VAND" },
  { .logo_res_id = RESOURCE_ID_VT, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 142, .name="Virginia Tech", .shortname="VT  " },
  { .logo_res_id = RESOURCE_ID_WAKE, .color = GColorBrassARGB8, .icon_color = GColorBlackARGB8, .rival = 78, .name="Wake Forest", .shortname="WAKE" },
  { .logo_res_id = RESOURCE_ID_WASHINGTON, .color = GColorIndigoARGB8, .icon_color = GColorWhiteARGB8, .rival = 91, .name="Washington", .shortname="WASH" },
  { .logo_res_id = RESOURCE_ID_WASHINGTONST, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 146, .name="Washington State", .shortname="WSU " },
  { .logo_res_id = RESOURCE_ID_WESTERNMICHIGAN, .color = GColorBulgarianRoseARGB8, .icon_color = GColorWhiteARGB8, .rival = 22, .name="Western Michigan", .shortname="WMU " },
  { .logo_res_id = RESOURCE_ID_WISCONSIN, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 71, .name="Wisconsin", .shortname="WIS " },
  { .logo_res_id = RESOURCE_ID_WKU, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 70, .name="Western Kentucky", .shortname="WKU " },
  { .logo_res_id = RESOURCE_ID_WVU, .color = GColorChromeYellowARGB8, .icon_color = GColorBlackARGB8, .rival = 97, .name="West Virginia", .shortname="WVU " },
  { .logo_res_id = RESOURCE_ID_WYOMING, .color = GColorWindsorTanARGB8, .icon_color = GColorWhiteARGB8, .rival = 29, .name="Wyoming", .shortname="WYO " },
};
#else
const Team TEAMS[] = {
  { .logo_res_id = RESOURCE_ID_ACC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_AIRFORCE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 10, .name="Air Force", .shortname="AFA " },
  { .logo_res_id = RESOURCE_ID_AKRON, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 54, .name="Akron", .shortname="AKRN" },
  { .logo_res_id = RESOURCE_ID_ALABAMA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 11, .name="Alabama", .shortname="BAMA" },
  { .logo_res_id = RESOURCE_ID_AMERICAN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_APPSTATE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 40, .name="App State", .shortname="APP " },
  { .logo_res_id = RESOURCE_ID_ARIZONA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 7, .name="Arizona", .shortname="ZONA" },
  { .logo_res_id = RESOURCE_ID_ARIZONAST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 6, .name="Arizona State", .shortname="ASU " },
  { .logo_res_id = RESOURCE_ID_ARKANSAS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 60, .name="Arkansas", .shortname="ARK " },
  { .logo_res_id = RESOURCE_ID_ARKANSASST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 64, .name="Arkansas State", .shortname="AKST" },
  { .logo_res_id = RESOURCE_ID_ARMY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 76, .name="Army", .shortname="ARMY" },
  { .logo_res_id = RESOURCE_ID_AUBURN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 3, .name="Auburn", .shortname="AUB " },
  { .logo_res_id = RESOURCE_ID_B1G, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_BALLST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 66, .name="Ball State", .shortname="BALL" },
  { .logo_res_id = RESOURCE_ID_BAYLOR, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 114, .name="Baylor", .shortname="BAY " },
  { .logo_res_id = RESOURCE_ID_BIG12, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_BOISEST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 38, .name="Boise State", .shortname="BSU " },
  { .logo_res_id = RESOURCE_ID_BOSTONCOLLEGE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 86, .name="Boston College", .shortname="BC  " },
  { .logo_res_id = RESOURCE_ID_BOWLINGGREEN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 121, .name="Bowling Green", .shortname="BGSU" },
  { .logo_res_id = RESOURCE_ID_BUFFALO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 115, .name="Buffalo", .shortname="BUFF" },
  { .logo_res_id = RESOURCE_ID_BYU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 138, .name="BYU", .shortname="BYU " },
  { .logo_res_id = RESOURCE_ID_CAL, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 111, .name="California", .shortname="CAL " },
  { .logo_res_id = RESOURCE_ID_CENTRALMICHIGAN, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 148, .name="Central Michigan", .shortname="CMU " },
  { .logo_res_id = RESOURCE_ID_CFB, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_CHAOS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_CINCI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 66, .name="Cincinnati", .shortname="CIN " },
  { .logo_res_id = RESOURCE_ID_CLEMSON, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 108, .name="Clemson", .shortname="CLEM" },
  { .logo_res_id = RESOURCE_ID_COASTAL, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 58, .name="Coastal Carolina", .shortname="CCU " },
  { .logo_res_id = RESOURCE_ID_COLORADO, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 29, .name="Colorado", .shortname="CU  " },
  { .logo_res_id = RESOURCE_ID_COLORADOST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 28, .name="Colorado State", .shortname="CSU " },
  { .logo_res_id = RESOURCE_ID_CUSA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_DELEWARE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 128, .name="Delaware", .shortname="DEL " },
  { .logo_res_id = RESOURCE_ID_DUKE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 134, .name="Duke", .shortname="DUKE" },
  { .logo_res_id = RESOURCE_ID_EASTERNMICHIGAN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 22, .name="Eastern Michigan", .shortname="EMU " },
  { .logo_res_id = RESOURCE_ID_ECU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 62, .name="East Carolina", .shortname="ECU " },
  { .logo_res_id = RESOURCE_ID_FAU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 36, .name="Florida Atlantic", .shortname="FAU " },
  { .logo_res_id = RESOURCE_ID_FIU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 35, .name="Florida International", .shortname="FIU " },
  { .logo_res_id = RESOURCE_ID_FLORIDA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 39, .name="Florida", .shortname="UF  " },
  { .logo_res_id = RESOURCE_ID_FRESNOST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 105, .name="Fresno State", .shortname="FRES" },
  { .logo_res_id = RESOURCE_ID_FSU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 37, .name="Florida State", .shortname="FSU " },
  { .logo_res_id = RESOURCE_ID_GEORGIASOUTHERN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 41, .name="Georgia Southern", .shortname="GASO" },
  { .logo_res_id = RESOURCE_ID_GEORGIAST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 40, .name="Georgia State", .shortname="GSU " },
  { .logo_res_id = RESOURCE_ID_GEORGIATECH, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 129, .name="Georgia Tech", .shortname="GT  " },
  { .logo_res_id = RESOURCE_ID_HAWAII, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 38, .name="Hawai'i", .shortname="HAW " },
  { .logo_res_id = RESOURCE_ID_HOUSTON, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 99, .name="Houston", .shortname="HOU " },
  { .logo_res_id = RESOURCE_ID_ILLINOIS, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 85, .name="Illinois", .shortname="ILL " },
  { .logo_res_id = RESOURCE_ID_INDEPENDENT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_INDIANA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 98, .name="Indiana", .shortname="IND " },
  { .logo_res_id = RESOURCE_ID_IOWA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 49, .name="Iowa", .shortname="IOWA" },
  { .logo_res_id = RESOURCE_ID_IOWAST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 48, .name="Iowa State", .shortname="ISU " },
  { .logo_res_id = RESOURCE_ID_JAXST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 122, .name="Jacksonville State", .shortname="JSU " },
  { .logo_res_id = RESOURCE_ID_JMU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 87, .name="James Madison", .shortname="JMU " },
  { .logo_res_id = RESOURCE_ID_KANSAS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 74, .name="Kansas", .shortname="KU  " },
  { .logo_res_id = RESOURCE_ID_KENNESAWST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 41, .name="Kennesaw State", .shortname="KSU " },
  { .logo_res_id = RESOURCE_ID_KENTST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 2, .name="Kent State", .shortname="KENT" },
  { .logo_res_id = RESOURCE_ID_KENTUCKY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 59, .name="Kentucky", .shortname="UK  " },
  { .logo_res_id = RESOURCE_ID_KSTATE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 52, .name="Kansas State", .shortname="KSU " },
  { .logo_res_id = RESOURCE_ID_LATECH, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 110, .name="Louisiana Tech", .shortname="LT  " },
  { .logo_res_id = RESOURCE_ID_LIBERTY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 51, .name="Liberty", .shortname="LIB " },
  { .logo_res_id = RESOURCE_ID_LOUISVILLE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 55, .name="Louisville", .shortname="LOU " },
  { .logo_res_id = RESOURCE_ID_LSU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 3, .name="LSU", .shortname="LSU " },
  { .logo_res_id = RESOURCE_ID_MAC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_MARSHALL, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 34, .name="Marshall", .shortname="HERD" },
  { .logo_res_id = RESOURCE_ID_MARYLAND, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 96, .name="Maryland", .shortname="MD  " },
  { .logo_res_id = RESOURCE_ID_MEMPHIS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 125, .name="Memphis", .shortname="MEM " },
  { .logo_res_id = RESOURCE_ID_METEOR, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_MIAMIOH, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 25, .name="Miami (OH)", .shortname="M-OH" },
  { .logo_res_id = RESOURCE_ID_MIAMI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 39, .name="Miami", .shortname="MIA " },
  { .logo_res_id = RESOURCE_ID_MICHIGAN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 93, .name="Michigan", .shortname="MICH" },
  { .logo_res_id = RESOURCE_ID_MICHIGANST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 68, .name="Michigan State", .shortname="MSU " },
  { .logo_res_id = RESOURCE_ID_MIDTENNST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 150, .name="Middle Tennessee", .shortname="MTSU" },
  { .logo_res_id = RESOURCE_ID_MINNESOTA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 149, .name="Minnesota", .shortname="MINN" },
  { .logo_res_id = RESOURCE_ID_MISSOURIST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 8, .name="Missouri State", .shortname="MOST" },
  { .logo_res_id = RESOURCE_ID_MISSST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 90, .name="Mississippi State", .shortname="MSST" },
  { .logo_res_id = RESOURCE_ID_MISSOURI, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 52, .name="Missouri", .shortname="MIZZ" },
  { .logo_res_id = RESOURCE_ID_MW, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_NAVY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 10, .name="Navy", .shortname="NAVY" },
  { .logo_res_id = RESOURCE_ID_NCAA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_NCST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 134, .name="NC State", .shortname="NCST" },
  { .logo_res_id = RESOURCE_ID_NDSU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 152, .name="North Dakota State", .shortname="NDSU" },
  { .logo_res_id = RESOURCE_ID_NEBRASKA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 48, .name="Nebraska", .shortname="NEB " },
  { .logo_res_id = RESOURCE_ID_NEVADA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 135, .name="Nevada", .shortname="NEV " },
  { .logo_res_id = RESOURCE_ID_NEWMEXICO, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 83, .name="New Mexico", .shortname="UNM " },
  { .logo_res_id = RESOURCE_ID_NEWMEXICOST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 82, .name="New Mexico State", .shortname="NMSU" },
  { .logo_res_id = RESOURCE_ID_NIU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 13, .name="Northern Illinois", .shortname="NIU " },
  { .logo_res_id = RESOURCE_ID_NORTHWESTERN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 45, .name="Northwestern", .shortname="NU  " },
  { .logo_res_id = RESOURCE_ID_NOTREDAME, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 109, .name="Notre Dame", .shortname="ND  " },
  { .logo_res_id = RESOURCE_ID_ODU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 51, .name="Old Dominion", .shortname="ODU " },
  { .logo_res_id = RESOURCE_ID_OHIO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 66, .name="Ohio", .shortname="OHIO" },
  { .logo_res_id = RESOURCE_ID_OKST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 94, .name="Oklahoma State", .shortname="OKST" },
  { .logo_res_id = RESOURCE_ID_OLEMISS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 73, .name="Ole Miss", .shortname="MISS" },
  { .logo_res_id = RESOURCE_ID_OREGON, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 146, .name="Oregon", .shortname="ORE " },
  { .logo_res_id = RESOURCE_ID_OREGONST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 91, .name="Oregon State", .shortname="ORST" },
  { .logo_res_id = RESOURCE_ID_OHIOST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 68, .name="Ohio State", .shortname="OSU " },
  { .logo_res_id = RESOURCE_ID_OKLAHOMA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 117, .name="Oklahoma", .shortname="OU  " },
  { .logo_res_id = RESOURCE_ID_PAC12, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_PENNST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 93, .name="Penn State", .shortname="PSU " },
  { .logo_res_id = RESOURCE_ID_PITT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 151, .name="Pittsburgh", .shortname="PITT" },
  { .logo_res_id = RESOURCE_ID_PURDUE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 47, .name="Purdue", .shortname="PUR " },
  { .logo_res_id = RESOURCE_ID_RICE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 44, .name="Rice", .shortname="RICE" },
  { .logo_res_id = RESOURCE_ID_RUTGERS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 63, .name="Rutgers", .shortname="RUTG" },
  { .logo_res_id = RESOURCE_ID_SACST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 38, .name="Sacramento State", .shortname="SAC " },
  { .logo_res_id = RESOURCE_ID_SHSU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 119, .name="Sam Houston", .shortname="SHSU" },
  { .logo_res_id = RESOURCE_ID_SDSU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 38, .name="San Diego State", .shortname="SDSU" },
  { .logo_res_id = RESOURCE_ID_SEC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_SJSU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 38, .name="San José State", .shortname="SJSU" },
  { .logo_res_id = RESOURCE_ID_SMU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 114, .name="SMU", .shortname="SMU " },
  { .logo_res_id = RESOURCE_ID_USA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 122, .name="South Alabama", .shortname="USA " },
  { .logo_res_id = RESOURCE_ID_GAMECOCK, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 26, .name="South Carolina", .shortname="SC  " },
  { .logo_res_id = RESOURCE_ID_SOUTHERNCAL, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 86, .name="USC", .shortname="USC " },
  { .logo_res_id = RESOURCE_ID_SOUTHERNMISS, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 57, .name="Southern Miss", .shortname="USM " },
  { .logo_res_id = RESOURCE_ID_STANFORD, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 21, .name="Stanford", .shortname="STAN" },
  { .logo_res_id = RESOURCE_ID_SUNBELT, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 77, .name="PLACEHOLDER", .shortname="PLCH" },
  { .logo_res_id = RESOURCE_ID_SYRACUSE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 97, .name="Syracuse", .shortname="CUSE" },
  { .logo_res_id = RESOURCE_ID_TCU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 14, .name="TCU", .shortname="TCU " },
  { .logo_res_id = RESOURCE_ID_TEMPLE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 19, .name="Temple", .shortname="TEMP" },
  { .logo_res_id = RESOURCE_ID_TENNESSEE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 3, .name="Tennessee", .shortname="TENN" },
  { .logo_res_id = RESOURCE_ID_TEXAS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 94, .name="Texas", .shortname="TEX " },
  { .logo_res_id = RESOURCE_ID_ATM, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 117, .name="Texas A&M", .shortname="A&M " },
  { .logo_res_id = RESOURCE_ID_TEXASST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 141, .name="Texas State", .shortname="TXST" },
  { .logo_res_id = RESOURCE_ID_TEXASTECH, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 117, .name="Texas Tech", .shortname="TTU " },
  { .logo_res_id = RESOURCE_ID_TOLEDO, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 18, .name="Toledo", .shortname="TOL " },
  { .logo_res_id = RESOURCE_ID_TROY, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 107, .name="Troy", .shortname="TROY" },
  { .logo_res_id = RESOURCE_ID_TULANE, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 110, .name="Tulane", .shortname="TULN" },
  { .logo_res_id = RESOURCE_ID_TULSA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 89, .name="Tulsa", .shortname="TLSA" },
  { .logo_res_id = RESOURCE_ID_UAB, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 64, .name="UAB", .shortname="UAB " },
  { .logo_res_id = RESOURCE_ID_UCF, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 137, .name="UCF", .shortname="UCF " },
  { .logo_res_id = RESOURCE_ID_UCLA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 109, .name="UCLA", .shortname="UCLA" },
  { .logo_res_id = RESOURCE_ID_UCONN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 132, .name="UConn", .shortname="CONN" },
  { .logo_res_id = RESOURCE_ID_UGA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 42, .name="Georgia", .shortname="UGA " },
  { .logo_res_id = RESOURCE_ID_ULL, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 131, .name="Louisiana", .shortname="ULL " },
  { .logo_res_id = RESOURCE_ID_ULM, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 130, .name="UL Monroe", .shortname="ULM " },
  { .logo_res_id = RESOURCE_ID_UMASS, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 128, .name="Massachusetts", .shortname="MASS" },
  { .logo_res_id = RESOURCE_ID_UNCC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 5, .name="Charlotte", .shortname="CLT " },
  { .logo_res_id = RESOURCE_ID_UNC, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 32, .name="North Carolina", .shortname="UNC " },
  { .logo_res_id = RESOURCE_ID_UNLV, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 81, .name="UNLV", .shortname="UNLV" },
  { .logo_res_id = RESOURCE_ID_UNT, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 141, .name="North Texas", .shortname="UNT " },
  { .logo_res_id = RESOURCE_ID_USF, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 126, .name="South Florida", .shortname="USF " },
  { .logo_res_id = RESOURCE_ID_UTAH, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 20, .name="Utah", .shortname="UTAH" },
  { .logo_res_id = RESOURCE_ID_UTAHST, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 138, .name="Utah State", .shortname="USU " },
  { .logo_res_id = RESOURCE_ID_UTEP, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 83, .name="UTEP", .shortname="UTEP" },
  { .logo_res_id = RESOURCE_ID_UTSA, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 119, .name="UTSA", .shortname="UTSA" },
  { .logo_res_id = RESOURCE_ID_UVA, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 144, .name="Virginia", .shortname="UVA " },
  { .logo_res_id = RESOURCE_ID_VANDY, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 116, .name="Vanderbilt", .shortname="VAND" },
  { .logo_res_id = RESOURCE_ID_VT, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 142, .name="Virginia Tech", .shortname="VT  " },
  { .logo_res_id = RESOURCE_ID_WAKE, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 78, .name="Wake Forest", .shortname="WAKE" },
  { .logo_res_id = RESOURCE_ID_WASHINGTON, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 91, .name="Washington", .shortname="WASH" },
  { .logo_res_id = RESOURCE_ID_WASHINGTONST, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 146, .name="Washington State", .shortname="WSU " },
  { .logo_res_id = RESOURCE_ID_WESTERNMICHIGAN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 22, .name="Western Michigan", .shortname="WMU " },
  { .logo_res_id = RESOURCE_ID_WISCONSIN, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 71, .name="Wisconsin", .shortname="WIS " },
  { .logo_res_id = RESOURCE_ID_WKU, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 70, .name="Western Kentucky", .shortname="WKU " },
  { .logo_res_id = RESOURCE_ID_WVU, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 97, .name="West Virginia", .shortname="WVU " },
  { .logo_res_id = RESOURCE_ID_WYOMING, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 29, .name="Wyoming", .shortname="WYO " },
};
#endif


API_Info API_DATA[] = {
  { .name = "Air Force", .id = 1 },
  { .name = "Akron", .id = 2 },
  { .name = "Alabama", .id = 3 },
  { .name = "App State", .id = 5 },
  { .name = "Arizona", .id = 6 },
  { .name = "Arizona State", .id = 7 },
  { .name = "Arkansas", .id = 8 },
  { .name = "Arkansas State", .id = 9 },
  { .name = "Army", .id = 10 },
  { .name = "Auburn", .id = 11 },
  { .name = "Ball State", .id = 13 },
  { .name = "Baylor", .id = 14 },
  { .name = "Boise State", .id = 16 },
  { .name = "Boston College", .id = 17 },
  { .name = "Bowling Green", .id = 18 },
  { .name = "Buffalo", .id = 19 },
  { .name = "BYU", .id = 20 },
  { .name = "California", .id = 21 },
  { .name = "Central Michigan", .id = 22 },
  { .name = "Cincinnati", .id = 25 },
  { .name = "Clemson", .id = 26 },
  { .name = "Coastal Carolina", .id = 27 },
  { .name = "Colorado", .id = 28 },
  { .name = "Colorado State", .id = 29 },
  { .name = "Delaware", .id = 31 },
  { .name = "Duke", .id = 32 },
  { .name = "Eastern Michigan", .id = 33 },
  { .name = "East Carolina", .id = 34 },
  { .name = "Florida Atlantic", .id = 35 },
  { .name = "Florida International", .id = 36 },
  { .name = "Florida", .id = 37 },
  { .name = "Fresno State", .id = 38 },
  { .name = "Florida State", .id = 39 },
  { .name = "Georgia Southern", .id = 40 },
  { .name = "Georgia State", .id = 41 },
  { .name = "Georgia Tech", .id = 42 },
  { .name = "Hawai'i", .id = 43 },
  { .name = "Houston", .id = 44 },
  { .name = "Illinois", .id = 45 },
  { .name = "Indiana", .id = 47 },
  { .name = "Iowa", .id = 48 },
  { .name = "Iowa State", .id = 49 },
  { .name = "Jacksonville State", .id = 50 },
  { .name = "James Madison", .id = 51 },
  { .name = "Kansas", .id = 52 },
  { .name = "Kennesaw State", .id = 53 },
  { .name = "Kent State", .id = 54 },
  { .name = "Kentucky", .id = 55 },
  { .name = "Kansas State", .id = 56 },
  { .name = "Louisiana Tech", .id = 57 },
  { .name = "Liberty", .id = 58 },
  { .name = "Louisville", .id = 59 },
  { .name = "LSU", .id = 60 },
  { .name = "Marshall", .id = 62 },
  { .name = "Maryland", .id = 63 },
  { .name = "Memphis", .id = 64 },
  { .name = "Miami (OH)", .id = 66 },
  { .name = "Miami", .id = 67 },
  { .name = "Michigan", .id = 68 },
  { .name = "Michigan State", .id = 69 },
  { .name = "Middle Tennessee", .id = 70 },
  { .name = "Minnesota", .id = 71 },
  { .name = "Missouri State", .id = 72 },
  { .name = "Mississippi State", .id = 73 },
  { .name = "Missouri", .id = 74 },
  { .name = "Navy", .id = 76 },
  { .name = "NC State", .id = 78 },
  { .name = "North Dakota State", .id = 79 },
  { .name = "Nebraska", .id = 80 },
  { .name = "Nevada", .id = 81 },
  { .name = "New Mexico", .id = 82 },
  { .name = "New Mexico State", .id = 83 },
  { .name = "Northern Illinois", .id = 84 },
  { .name = "Northwestern", .id = 85 },
  { .name = "Notre Dame", .id = 86 },
  { .name = "Old Dominion", .id = 87 },
  { .name = "Ohio", .id = 88 },
  { .name = "Oklahoma State", .id = 89 },
  { .name = "Ole Miss", .id = 90 },
  { .name = "Oregon", .id = 91 },
  { .name = "Oregon State", .id = 92 },
  { .name = "Ohio State", .id = 93 },
  { .name = "Oklahoma", .id = 94 },
  { .name = "Penn State", .id = 96 },
  { .name = "Pittsburgh", .id = 97 },
  { .name = "Purdue", .id = 98 },
  { .name = "Rice", .id = 99 },
  { .name = "Rutgers", .id = 100 },
  { .name = "Sacramento State", .id = 101 },
  { .name = "Sam Houston", .id = 102 },
  { .name = "San Diego State", .id = 103 },
  { .name = "San José State", .id = 105 },
  { .name = "SMU", .id = 106 },
  { .name = "South Alabama", .id = 107 },
  { .name = "South Carolina", .id = 108 },
  { .name = "USC", .id = 109 },
  { .name = "Southern Miss", .id = 110 },
  { .name = "Stanford", .id = 111 },
  { .name = "Syracuse", .id = 113 },
  { .name = "TCU", .id = 114 },
  { .name = "Temple", .id = 115 },
  { .name = "Tennessee", .id = 116 },
  { .name = "Texas", .id = 117 },
  { .name = "Texas A&M", .id = 118 },
  { .name = "Texas State", .id = 119 },
  { .name = "Texas Tech", .id = 120 },
  { .name = "Toledo", .id = 121 },
  { .name = "Troy", .id = 122 },
  { .name = "Tulane", .id = 123 },
  { .name = "Tulsa", .id = 124 },
  { .name = "UAB", .id = 125 },
  { .name = "UCF", .id = 126 },
  { .name = "UCLA", .id = 127 },
  { .name = "UConn", .id = 128 },
  { .name = "Georgia", .id = 129 },
  { .name = "Louisiana", .id = 130 },
  { .name = "UL Monroe", .id = 131 },
  { .name = "Massachusetts", .id = 132 },
  { .name = "Charlotte", .id = 133 },
  { .name = "North Carolina", .id = 134 },
  { .name = "UNLV", .id = 135 },
  { .name = "North Texas", .id = 136 },
  { .name = "South Florida", .id = 137 },
  { .name = "Utah", .id = 138 },
  { .name = "Utah State", .id = 139 },
  { .name = "UTEP", .id = 140 },
  { .name = "UTSA", .id = 141 },
  { .name = "Virginia", .id = 142 },
  { .name = "Vanderbilt", .id = 143 },
  { .name = "Virginia Tech", .id = 144 },
  { .name = "Wake Forest", .id = 145 },
  { .name = "Washington", .id = 146 },
  { .name = "Washington State", .id = 147 },
  { .name = "Western Michigan", .id = 148 },
  { .name = "Wisconsin", .id = 149 },
  { .name = "Western Kentucky", .id = 150 },
  { .name = "West Virginia", .id = 151 },
  { .name = "Wyoming", .id = 152 },
};

// Number of entries in API_DATA — sized for the test-bed roster, not the
// full 154-team NUM_TEAMS. Use this (not NUM_TEAMS) when iterating/parsing
// so the small test roster doesn't require touching parser code as the
// real roster grows.
const size_t API_DATA_COUNT = sizeof(API_DATA) / sizeof(API_DATA[0]);

// Define the count based on the array
const size_t TEAMS_COUNT = sizeof(TEAMS) / sizeof(TEAMS[0]);
