// teams.c
#include "teams.h" // Include the header to get the 'Team' type


#if defined(PBL_COLOR)
const Team TEAMS[] = {
  { .logo_res_id = RESOURCE_ID_CLEMSON, .color = GColorOrangeARGB8, .icon_color = GColorWhiteARGB8, .rival = 1, .name="Clemson", .shortname="CLEM" },
  { .logo_res_id = RESOURCE_ID_GAMECOCK, .color = GColorDarkCandyAppleRedARGB8, .icon_color = GColorWhiteARGB8, .rival = 0, .name="South Carolina", .shortname="SC" },
};
#else
const Team TEAMS[] = {
  { .logo_res_id = RESOURCE_ID_CLEMSON, .color = GColorWhiteARGB8, .icon_color = GColorBlackARGB8, .rival = 1, .name="Clemson", .shortname="CLEM" },
  { .logo_res_id = RESOURCE_ID_GAMECOCK, .color = GColorBlackARGB8, .icon_color = GColorWhiteARGB8, .rival = 0, .name="South Carolina", .shortname="SC" },
};
#endif


API_Info API_DATA[] = {
  //{ .name = "Air Force", .id = 1, .vs_id = 10, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Clemson", .id = 0, .vs_id = 1, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "South Carolina", .id = 1, .vs_id = 0, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Akron", .id = 2, .vs_id = 54, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Alabama", .id = 3, .vs_id = 11, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "App State", .id = 5, .vs_id = 40, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Arizona", .id = 6, .vs_id = 7, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Arizona State", .id = 7, .vs_id = 6, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Arkansas", .id = 8, .vs_id = 60, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Arkansas State", .id = 9, .vs_id = 64, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Army", .id = 10, .vs_id = 76, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Auburn", .id = 11, .vs_id = 3, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Ball State", .id = 13, .vs_id = 66, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Baylor", .id = 14, .vs_id = 114, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Boise State", .id = 16, .vs_id = 38, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Boston College", .id = 17, .vs_id = 86, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Bowling Green", .id = 18, .vs_id = 121, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Buffalo", .id = 19, .vs_id = 115, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "BYU", .id = 20, .vs_id = 138, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "California", .id = 21, .vs_id = 111, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Central Michigan", .id = 22, .vs_id = 148, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Cincinnati", .id = 25, .vs_id = 66, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  //{ .name = "Clemson", .id = 26, .vs_id = 108, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Coastal Carolina", .id = 27, .vs_id = 58, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Colorado", .id = 28, .vs_id = 29, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Colorado State", .id = 29, .vs_id = 28, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Delaware", .id = 31, .vs_id = 128, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Duke", .id = 32, .vs_id = 134, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Eastern Michigan", .id = 33, .vs_id = 22, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "East Carolina", .id = 34, .vs_id = 62, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Florida Atlantic", .id = 35, .vs_id = 36, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Florida International", .id = 36, .vs_id = 35, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Florida", .id = 37, .vs_id = 39, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Fresno State", .id = 38, .vs_id = 105, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Florida State", .id = 39, .vs_id = 37, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Georgia Southern", .id = 40, .vs_id = 41, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Georgia State", .id = 41, .vs_id = 40, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Georgia Tech", .id = 42, .vs_id = 129, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Hawai'i", .id = 43, .vs_id = 38, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Houston", .id = 44, .vs_id = 99, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Illinois", .id = 45, .vs_id = 85, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Indiana", .id = 47, .vs_id = 98, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Iowa", .id = 48, .vs_id = 49, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Iowa State", .id = 49, .vs_id = 48, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Jacksonville State", .id = 50, .vs_id = 122, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "James Madison", .id = 51, .vs_id = 87, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Kansas", .id = 52, .vs_id = 74, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Kennesaw State", .id = 53, .vs_id = 41, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Kent State", .id = 54, .vs_id = 2, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Kentucky", .id = 55, .vs_id = 59, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Kansas State", .id = 56, .vs_id = 52, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Louisiana Tech", .id = 57, .vs_id = 110, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Liberty", .id = 58, .vs_id = 51, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Louisville", .id = 59, .vs_id = 55, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "LSU", .id = 60, .vs_id = 3, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Marshall", .id = 62, .vs_id = 34, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Maryland", .id = 63, .vs_id = 96, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Memphis", .id = 64, .vs_id = 125, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Miami (OH)", .id = 66, .vs_id = 25, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Miami", .id = 67, .vs_id = 39, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Michigan", .id = 68, .vs_id = 93, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Michigan State", .id = 69, .vs_id = 68, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Middle Tennessee", .id = 70, .vs_id = 150, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Minnesota", .id = 71, .vs_id = 149, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Missouri State", .id = 72, .vs_id = 8, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Mississippi State", .id = 73, .vs_id = 90, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Missouri", .id = 74, .vs_id = 52, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Navy", .id = 76, .vs_id = 10, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "NC State", .id = 78, .vs_id = 134, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "North Dakota State", .id = 79, .vs_id = 152, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Nebraska", .id = 80, .vs_id = 48, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Nevada", .id = 81, .vs_id = 135, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "New Mexico", .id = 82, .vs_id = 83, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "New Mexico State", .id = 83, .vs_id = 82, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Northern Illinois", .id = 84, .vs_id = 13, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Northwestern", .id = 85, .vs_id = 45, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Notre Dame", .id = 86, .vs_id = 109, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Old Dominion", .id = 87, .vs_id = 51, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Ohio", .id = 88, .vs_id = 66, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Oklahoma State", .id = 89, .vs_id = 94, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Ole Miss", .id = 90, .vs_id = 73, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Oregon", .id = 91, .vs_id = 146, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Oregon State", .id = 92, .vs_id = 91, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Ohio State", .id = 93, .vs_id = 68, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Oklahoma", .id = 94, .vs_id = 117, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Penn State", .id = 96, .vs_id = 93, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Pittsburgh", .id = 97, .vs_id = 151, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Purdue", .id = 98, .vs_id = 47, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Rice", .id = 99, .vs_id = 44, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Rutgers", .id = 100, .vs_id = 63, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Sacramento State", .id = 101, .vs_id = 38, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Sam Houston", .id = 102, .vs_id = 119, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "San Diego State", .id = 103, .vs_id = 38, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "San José State", .id = 105, .vs_id = 38, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "SMU", .id = 106, .vs_id = 114, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "South Alabama", .id = 107, .vs_id = 122, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  //{ .name = "South Carolina", .id = 108, .vs_id = 26, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "USC", .id = 109, .vs_id = 86, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Southern Miss", .id = 110, .vs_id = 57, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Stanford", .id = 111, .vs_id = 21, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Syracuse", .id = 113, .vs_id = 97, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "TCU", .id = 114, .vs_id = 14, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Temple", .id = 115, .vs_id = 19, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Tennessee", .id = 116, .vs_id = 3, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Texas", .id = 117, .vs_id = 94, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Texas A&M", .id = 118, .vs_id = 117, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Texas State", .id = 119, .vs_id = 141, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Texas Tech", .id = 120, .vs_id = 117, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Toledo", .id = 121, .vs_id = 18, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Troy", .id = 122, .vs_id = 107, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Tulane", .id = 123, .vs_id = 110, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Tulsa", .id = 124, .vs_id = 89, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "UAB", .id = 125, .vs_id = 64, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "UCF", .id = 126, .vs_id = 137, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "UCLA", .id = 127, .vs_id = 109, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "UConn", .id = 128, .vs_id = 132, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Georgia", .id = 129, .vs_id = 42, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Louisiana", .id = 130, .vs_id = 131, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "UL Monroe", .id = 131, .vs_id = 130, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Massachusetts", .id = 132, .vs_id = 128, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Charlotte", .id = 133, .vs_id = 5, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "North Carolina", .id = 134, .vs_id = 32, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "UNLV", .id = 135, .vs_id = 81, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "North Texas", .id = 136, .vs_id = 141, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "South Florida", .id = 137, .vs_id = 126, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Utah", .id = 138, .vs_id = 20, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Utah State", .id = 139, .vs_id = 138, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "UTEP", .id = 140, .vs_id = 83, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "UTSA", .id = 141, .vs_id = 119, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Virginia", .id = 142, .vs_id = 144, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Vanderbilt", .id = 143, .vs_id = 116, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Virginia Tech", .id = 144, .vs_id = 142, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Wake Forest", .id = 145, .vs_id = 78, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Washington", .id = 146, .vs_id = 91, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Washington State", .id = 147, .vs_id = 146, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Western Michigan", .id = 148, .vs_id = 22, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Wisconsin", .id = 149, .vs_id = 71, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Western Kentucky", .id = 150, .vs_id = 70, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "West Virginia", .id = 151, .vs_id = 97, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
  { .name = "Wyoming", .id = 152, .vs_id = 29, .score = 0, .vs_score = 0, .gametime = 0, .ranking = 0, .wins = 0, .postseasonGames = 0, .postseasonWins = 0, .postseasonLosses = 0 },
};

// Number of entries in API_DATA — sized for the test-bed roster, not the
// full 154-team NUM_TEAMS. Use this (not NUM_TEAMS) when iterating/parsing
// so the small test roster doesn't require touching parser code as the
// real roster grows.
const size_t API_DATA_COUNT = sizeof(API_DATA) / sizeof(API_DATA[0]);

// Define the count based on the array
const size_t TEAMS_COUNT = sizeof(TEAMS) / sizeof(TEAMS[0]);
